### ISSUE TITLE
undefined symbol: _QPexit

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#1003]
I was hit this linker error when trying to build SNAP (https://github.com/lanl/SNAP)

```
flang -O3   -o gsnap global.o snap_main.o utils.o version.o plib.o geom.o sn.o data.o control.o input.o setup.o dealloc.o translv.o solvar.o outer.o expxs.o inner.o sweep.o octsweep.o dim1_sweep.o dim3_sweep.o output.o time.o mms.o analyze.o thrd_comm.o mkba_sweep.o
ld.lld: error: undefined symbol: _QPexit
>>> referenced by <stdin>:583 (/home/ryuta/workspace/flang/SNAP/SNAP/src/<stdin>:583)
>>>               utils.o:(_QMutils_modulePstop_run)
```

FEHM (https://github.com/lanl/FEHM), NEXMD (https://github.com/lanl/NEXMD), MUMPS (http://mumps.enseeiht.fr/)
depends on `EXIT`, just to name a few.

[EXIT GNU Fortran](https://gcc.gnu.org/onlinedocs/gfortran/EXIT.html#EXIT)
[EXIT Intel Fortran](https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/e-to-f/exit-statement.html)

**Comment by schweitzpgi** [comment]
As a (brittle) workaround, it is possible to use `sed` (or a similar tool) to replace `_QP[a-zA-Z0-9_]+` identifiers with other spellings. This can help achieve some degree of interoperability for the moment.
