### ISSUE TITLE
`Check-flang` fails from 82a41cb4613a1555c08e5e8f73d649b36d76ae99

### ISSUE THREAD

**Issue by Sameeranjoshi** [flang-compiler/f18-llvm-project#102]
FAIL: Flang :: Lower/end-to-end-character-assignment.f90 (201 of 400)
******************** TEST 'Flang :: Lower/end-to-end-character-assignment.f90' FAILED ********************
Exception in thread Thread-3:
...

**Comment by schweitzpgi** [comment]
Let's just revert for now?

**Comment by schweitzpgi** [comment]
Reverted the PR that caused regression.
