### ISSUE TITLE
fir-opt tests fail for out-of-tree builds

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18-llvm-project#1038]
When building f18 out-of-tree, the tests FIR/cg-ops.fir, Fir/fir-ops.fir, and Fir/fir-types.fir all fail.  I'd guess that the easiest one to debug would be the fir-types.fir failure.

**Comment by schweitzpgi** [comment]
Not able to reproduce. (After the rebase, I am getting compilation failures in Fortran/Semantics with OOT builds.)

**Comment by jeanPerier** [comment]
> (After the rebase, I am getting compilation failures in Fortran/Semantics with OOT builds.)

Are you working on a fix or do you have some error logs so that I can try to reproduce ?

**Comment by psteinfeld** [comment]
I just did in-tree and out-of-tree builds from the latest source in fir-dev, and everything builds and tests without error for me.

@schweitzpgi , unless you're still getting errors, I think we can close this.
