### ISSUE TITLE
No diagnostic given for illegal branch into middle fo where

### ISSUE THREAD

**Issue by mleair** [flang-compiler/f18-llvm-project#1048]
No diagnostic is not given for the following code:

Program branch_where
  Integer :: a(10),b(10)
  Where (a==1)
    b = -b
  Elsewhere
100 Where (a>5)
    End Where
  End Where
  Go To 100
End Program

**Comment by klausler** [comment]
A diagnostic message appears in today's fir-dev, but it's a warning, not an error.  I'll fix that.

**Comment by klausler** [comment]
A fix to the general problem is out for review elsewhere.

**Comment by schweitzpgi** [comment]
Works for me.
