### ISSUE TITLE
Multiple assertions with NAG test runs

### ISSUE THREAD

**Issue by svedan** [flang-compiler/f18-llvm-project#1115]
7 Assertion `resultType && "expect intrinsic function"' failed.
      2 Assertion `hasSymbol() && "variable is not nominal"' failed.
      2 Assertion `funcPointer && "dummy procedure or procedure pointer not in symbol map"' failed.
      1 Assertion `!x->base().IsSymbol()' failed.
      1 Assertion `i <= indices.size()' failed.
      1 Assertion `idx < size()' failed.
      1 Assertion `(finalized || !cleanupAdded) && "statement context is not empty and not finalized"' failed.

We need these cleaned up.  If these are associated with features that have not been implemented yet, we need To Do's stating that.

**Comment by psteinfeld** [comment]
I'm working on this now, and I want to know if I'm doing the right thing.  I've changed the compiler for the first assertion failure so that it now produces output that looks like this:
```
LLVM ERROR: /local/home/psteinfeld/cg/a1/flang/lib/Optimizer/Dialect/FIRType.cpp:833: not yet implemented building an array of BoxType
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./bin/bbc al13.f90 -o -
 #0 0x0000000001466dbc llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./bin/bbc+0x1466dbc)
 #1 0x0000000001464e54 llvm::sys::RunSignalHandlers() (./bin/bbc+0x1464e54)
 #2 0x0000000001464fb3 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fd377bffdd0 __restore_rt sigaction.c:0:0

```
@sscalpone, is this what you want?

**Comment by sscalpone** [comment]
The message should reference a line in the users program. The message should say the Fortean feature the can't be complied. So maybe the assertion needs to be higher up in the stack.

________________________________

**Comment by svedan** [comment]
Do you want me to open a new issue to track the semantic check (or do you want to lump a few of these together)?
