### ISSUE TITLE
OpenMP parallel do with cycle compiles to "nothing".

### ISSUE THREAD

**Issue by Leporacanthicus** [flang-compiler/f18-llvm-project#1120]
The following code, you'd expect to print 2,3,4,5 (or some combination of those numbers in some order, at least)
```
program n
  integer :: i
  !$omp parallel do schedule(static, 1) num_threads(5)
  do i = 1,5
     if (i == 1) cycle
     print *,i
  end do
  !$omp end parallel do
end program n
```
But for reasons that are not clear at this point, the code inside the do-loop is completely lost.

```
func @_QQmain() {
  %0 = fir.alloca i32 {bindc_name = "i", uniq_name = "_QEi"}
  %c5_i32 = constant 5 : i32
  omp.parallel num_threads(%c5_i32 : i32) {
    %c1_i32 = constant 1 : i32
    %c1_i32_0 = constant 1 : i32
    %c5_i32_1 = constant 5 : i32
    %c1_i32_2 = constant 1 : i32
    omp.wsloop (%arg0) : i32 = (%c1_i32_0) to (%c5_i32_1) step (%c1_i32_2) sched
ule(static = %c1_i32, none) inclusive {
      omp.yield
    }
    omp.terminator
  }
  return
}
```

Remove the `if (i == 1) cycle` and it produces correct code:
```
func @_QQmain() {
  %0 = fir.alloca i32 {bindc_name = "i", uniq_name = "_QEi"}
  %c5_i32 = constant 5 : i32
  omp.parallel num_threads(%c5_i32 : i32) {
    %c1_i32 = constant 1 : i32
    %c1_i32_0 = constant 1 : i32
    %c5_i32_1 = constant 5 : i32
    %c1_i32_2 = constant 1 : i32
    omp.wsloop (%arg0) : i32 = (%c1_i32_0) to (%c5_i32_1) step (%c1_i32_2) sched
ule(static = %c1_i32, none) inclusive {
      %c-1_i32 = constant -1 : i32
      %1 = fir.address_of(@_QQcl.2E2F6E657374696E672E66393000) : !fir.ref<!fir.c
har<1,14>>
      %2 = fir.convert %1 : (!fir.ref<!fir.char<1,14>>) -> !fir.ref<i8>
      %c6_i32 = constant 6 : i32
      %3 = fir.call @_FortranAioBeginExternalListOutput(%c-1_i32, %2, %c6_i32) :
 (i32, !fir.ref<i8>, i32) -> !fir.ref<i8>
      %4 = fir.convert %arg0 : (i32) -> i64
      %5 = fir.call @_FortranAioOutputInteger64(%3, %4) : (!fir.ref<i8>, i64) ->
 i1
      %6 = fir.call @_FortranAioEndIoStatement(%3) : (!fir.ref<i8>) -> i32
      omp.yield
    }
    omp.terminator
  }
  return
}
```

I have spent some time in the debugger on this, but I'm not sure exactly what is going wrong - I can see that a different block is created, and filled with the code for the print, but it seems be be placed in the wrong location, and later on it seems to go missing or be replaced by another block.

It should be noted that replacing the `if (i == 1) cycle` with `if (i /= 1) then ... print ... end if` works fine. As does this `goto` variant:

```
program n
  integer :: i
  !$omp parallel do schedule(static, 1) num_threads(5)
  do i = 1,5
     if (i == 1) goto 12
     print *,i
12  end do
  !$omp end parallel do
end program n
```
I will get back to this with comments to explain what my debugging has found so far....

To reproduce `bbc -emit-fir -I=/data//f18-llvm-project/build/../flang/module nesting.f90 -fopenmp` (nesting.f90 is the name of the source code above - bad name, I started out thinking it was a nested OpenMP issue - but it isn't anything to do with nesting!)

**Comment by kiranchandramohan** [comment]
If the presence of a cycle statement causes the lowering to not create a fir.do_loop and instead generate a CFG then I think the present codegen for the OpenMP work-sharing loop will not work. We expect the body to be structured and loop-like.

@schweitzpgi @jeanPerier any reason why we cannot lower to a fir.do_loop with a fir.if for the code following the cycle in this example?

**Comment by Leporacanthicus** [comment]
Sadly, the obvious solution to the problem does not help:
```
program d
  implicit none
  integer :: j
  integer :: i
  !$omp parallel do schedule(static, 1) num_threads(5) private(i, j)
  do i = 1,5
     j = 0
     do while (j < 5)
        print *, j
        j = j + 1
     end do
  end do
  !$omp end parallel do
end program d
```

**Comment by kiranchandramohan** [comment]
One of the things we should investigate is where blocks are created for unstructured code. Since unstructured code is not expected inside FIR operations, it is possible that blocks are created always in the region of the Function Operation. If there is unstructured code in OpenMP/OpenACC constructs then the unstructured blocks have to be created inside the OpenMP/OpenACC operation.

One place I found where the unstructured blocks are created is `createEmptyBlocks`. I don't know whether there are other places. It might be useful to check where the blocks corresponding to unstructured code in OpenMP constructs are created in `createEmptyBlocks`.
https://github.com/flang-compiler/f18-llvm-project/blob/ce56fc4abb6ac67dc56b760f10d45053bfcf8173/flang/lib/Lower/Bridge.cpp#L2452

**Comment by vdonaldson** [comment]
Yes, that could be the direction to take.  Function `createEmptyBlocks` is responsible for generating **all** "global" blocks in advance.  That allows the rest of the code to assume that forward as well as backward branch targets are valid.  A block is a global block if it could be the target of an explicit program branch or a fall through from another block.  A block is a "local" block if it can only be targeted by compiler generated branches.  The prime illustration of this distinction is that a loop preheader block is global, whereas the loop header block is local.  Preheader code may be appended to a predecessor block, so there need not always be a dedicated preheader block.  The local loop header block is always present, but is not visible outside the loop.

Reparenting a block from one region to another might be a good solution.  I don't immediately see a mechanism to do that, but that would have some nice properties if it works.  Another option is to delay generation of blocks in OpenMP regions until the region is entered.  That will only work if the compiler enforces a prohibition on branches into the region.  So the reparenting solution might be better if it works.  A third option is to generate duplicate blocks, and let dce clean up the old unused blocks.  That might be acceptable as this is likely to be a low frequency scenario.

**Comment by Leporacanthicus** [comment]
No, I don't think there's a `reparentBlock` function. There is a funciton `splitBlock` (not sure about the exact name), which we could use as a building block for a `reparentBlock`.

This would either need to go into the logic that adds the OpenMP construct itself, or be part of the `maybeStartBlock`.

If the compiler doesn't already forbid branches into (or out of?) OpenMP regions, it certainly should do so (I think it does, but I haven't tested it - I will test at some point later today). So it should be safe to move those blocks around.

**Comment by vdonaldson** [comment]
An initial test case using duplication compiles and executes correctly.  I've got some other issues to address, but this direction looks promising.

**Comment by vdonaldson** [comment]
With a workaround for the independent issue of an invalid error message: `CYCLE to construct outside of PARALLEL DO construct is not allowed`, the original test case now executes correctly.  Additional, related problems are covered in issue #1178, and possibly elsewhere.
