### ISSUE TITLE
Code generation is broken for SNAP

### ISSUE THREAD

**Issue by Leporacanthicus** [flang-compiler/f18-llvm-project#1176]
The following commit: f72c9754301e2a2edfd122aeb96861ea2a62f49b has been bisected to show a break in the SNAP application. The code compiles to a binary, but when running it, the result is not matching the expectation (and it takes ~2 minutes instead of 2 seconds to run).

It isn't clear exactly what is actually going wrong (I had a brief look at the code in that patch, and it looks simple enough and nothing obviously wrong).

I will try to find a small test-case.

**Comment by banach-space** [comment]
Closing as we have been able to build SNAP just fine. This is documented in https://github.com/flang-compiler/f18-llvm-project/issues/1341.
