### ISSUE TITLE
Pointer in private clause not handled correctly

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/f18-llvm-project#1229]
When I look at pointer in common block for both private clause and threadprivate directive, I found out that pointer in private clause is not processed correctly. Do you have time to look at it? Please notice that pointer to a scalar and pointer to an array, with and without SAVE attribute have different FIR processing.

Reported by @PeixinQiao. Please add a reproducer if you have one.

**Comment by PeixinQiao** [comment]
```
integer, pointer :: y1, y2(:)
integer, pointer, save :: y3, y4(:)
integer, target :: z1, z2(10)

!$omp parallel private(y1, y2, y3, y4)
  y1=>z1
  y2=>z2
  y3=>z1
  y4=>z2
!$omp end parallel
end
```
```
$ bbc -fopenmp -emit-fir test.f90 
error: loc("./test.f90":6:3): expr was not lowered to MutableBoxValue
LLVM ERROR: aborting
```
@kiranchandramohan Here is the test case.

**Comment by PeixinQiao** [comment]
@kiranchandramohan Can you take up this issue? I plan to go ahead with ordered clause codegen. Is this OK?

**Comment by kiranchandramohan** [comment]
OK. I will take it up @PeixinQiao.

**Comment by PeixinQiao** [comment]
@kiranchandramohan Thanks a lot.

**Comment by kiranchandramohan** [comment]
Fixed by https://reviews.llvm.org/D148570.
