### ISSUE TITLE
Read statements causes fortran runtime to hang

### ISSUE THREAD

**Issue by zacharyselk** [flang-compiler/f18-llvm-project#126]
When the program reaches a `read` statement it hangs indefinitely. Also if there is a `read` statement in the program `print` statements prior it do not seem to work either, as seen in the following fortran program:

```
      program main
      implicit none

      integer*8 :: i, j
      i = 1
      print *, i
      print *, "Hello\nWorld"

      do j = 1, 10000000000
         i = i + 1
      end do

      read(*,*) i
      print *, i

      do j = 1, 10000000000
      i = i + 1
      end do

      end program main
```

(I used the do loops and top to see what parts of the program were running)

**Comment by schweitzpgi** [comment]
@zacharyselk Do you know where this hangs? (I haven't investigated it yet.)

**Comment by sscalpone** [comment]
I will guess that input is blocking on a full read instead of handling terminal input as a special case because the program makes progress if you type ^D.  The loops aren't required to repro.  Note that the output isn't printed until you hit ^D too.

```
program main
      implicit none

      integer*8 :: i, j
      i = 1
      print *, i
      print *, "Hello\nWorld"

      read(*,*) i
      print *, i

      end program main
```

**Comment by klausler** [comment]
I'll take a look at it.

**Comment by sscalpone** [comment]
Fixed.
