### ISSUE TITLE
Convert the global option (nameLengthHashSize) in FIRBuilder.cpp to a value that can be stored in the Dialect.

### ISSUE THREAD

**Issue by kiranchandramohan** [flang-compiler/f18-llvm-project#1273]
Global Options are generally discouraged. Can we build the optimizer with -Werror=global-constructors by the way?

Convert the global option (nameLengthHashSize) in FIRBuilder.cpp to a value that can be stored in the Dialect.

**Comment by clementval** [comment]
https://reviews.llvm.org/D114630
