### ISSUE TITLE
#1126 Causing driver lowering to LLVM IR to fail

### ISSUE THREAD

**Issue by Sezoir** [flang-compiler/f18-llvm-project#1280]
## Summary
Bisection was shown that #1126 was causing a compile failure with the following reproducer.
## Reproducer:
```
MODULE bug_module
    REAL(8_4), ALLOCATABLE, DIMENSION(:) :: mu
    CONTAINS
    SUBROUTINE bug ( istat )
        INTEGER(4_4), INTENT(INOUT) :: istat
        IF ( istat > 0 ) RETURN
        w = zero
    END SUBROUTINE bug
END MODULE bug_module
```
## Expected Result:
Compiles fine with commit "Fix the runtime library order" (f4abd787cb3d162ec13629c91b6a8d68dafbc469).
## Actual Result:
```
flang-new -O3  -I /f18-llvm-project/flang/module -c bug.f90
flang-new: warning: argument unused during compilation: '-O3'
error: loc("./bug.f90":23:5): unreachable blocks were not converted
error: error in converting to CFG

error: Lowering to LLVM IR failed
error: loc("./bug.f90":21:45): cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: fir.global
error: failed to create the LLVM module
```

**Comment by banach-space** [comment]
Hi Josh,

Thanks for reporting this! I was able to re-produce it (btw, the warning about `-O3` is irrelevant here, so can be ignored). 

#1126 updates pass pipeline creation in `bbc` and CLOptions.inc, and IIUC, an inconsistency crept in:
- ` pm.addPass(mlir::createCanonicalizerPass());` in [bbc.cpp](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/tools/bbc/bbc.cpp#L27), vs
- `pm.addPass(mlir::createCanonicalizerPass(config));` in [CLOptions.inc](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/include/flang/Tools/CLOptions.inc#L106).

I was able to fix this issue by replacing `pm.addPass(mlir::createCanonicalizerPass(config));` with `pm.addPass(mlir::createCanonicalizerPass());` in "CLOptions.inc" (i.e. by making sure that `flang-new` and `bbc` use identical pass pipeline definition). So, IMO, we should just make sure that `flang-new`, `tco` and `bbc` share code for defining these pass pipelines.

This is not my area of expertise though, so might be missing something more obvious here. @clementval , WDYT? Also, I posted #1281 that contains the reproducer (fails "before" #1281, works fine "after").

**Comment by banach-space** [comment]
#1126 was reverted and a new PR was opened that does not break `flang-new`: https://github.com/flang-compiler/f18-llvm-project/pull/1287. I'm closing this for now. We can re-open if this comes back.
