### ISSUE TITLE
FORMAT with ASSIGN not implemented (fm111, fm252)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#130]
e.g.,
```fortran
  ASSIGN 1010 TO i
1010 FORMAT ...
  WRITE(i02, i)
```

**Comment by schweitzpgi** [comment]
done?

**Comment by vdonaldson** [comment]
No; PR #183 made the label and format information available, but the selection code isn't done.

**Comment by schweitzpgi** [comment]
Any progress on this one @zacharyselk ?

**Comment by zacharyselk** [comment]
It is getting there. Currently I am only stuck on trying to generate a character pointer without having the compiler crash.
