### ISSUE TITLE
UNREACHABLE doesn't offer a hint to the user about what code might be problematic

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#133]
UNREACHABLE executed at f18-llvm-project/flang/lib/Lower/Bridge.cpp:658!

**Comment by jeanPerier** [comment]
Is this the same error report as #134 ? The source location of the unreachable you gave is the same.

**Comment by schweitzpgi** [comment]
We're not going to fix this.

**Comment by sscalpone** [comment]
> Is this the same error report as #134 ?

This issue is about the lack of traceability back to the source code.

**Comment by sscalpone** [comment]
This is helpful!

`error: loc("/proj/ta/tests/fcvs/src/fm097.f":383:7): 'fir.cmpf' op requires all operands to have the same type`

**Comment by schweitzpgi** [comment]
Targeted messages have been added.
