### ISSUE TITLE
invalid assigned goto target

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#134]
flang -c  fcvs/src/fm013.f
invalid assigned goto target
UNREACHABLE executed at /local/home/sjs/flang/f18-llvm-project/flang/lib/Lower/Bridge.cpp:658!

**Comment by schweitzpgi** [comment]
fm013... PASS

Looks fixed to me.

**Comment by sscalpone** [comment]
Verified!
