### ISSUE TITLE
/usr/local/bin/flang: line 259: conditional binary operator expected

### ISSUE THREAD

**Issue by jeffhammond** [flang-compiler/f18-llvm-project#1345]
The Bash that ships with MacOS 11.5.1 (Big Sur) does not like `if [[ -v $FLANG_FC ]]; then`.

It may be prudent to do more testing on non-Linux OS like MacOS and BSD to verify the portability of the driver script.

```
% make                    
/usr/local/bin/flang -g -O3 -mtune=native -ffast-math -Wall  -Wno-ignored-attributes -Wno-deprecated-declarations -DRADIUS=2 -DSTAR -DPGI -c prk_mod.F90 -o prk_mod.o
/usr/local/bin/flang: line 259: conditional binary operator expected
make: *** [prk.mod] Error 2
```

Closely related to #1344

**Comment by banach-space** [comment]
Hi @jeffhammond , have you tried updating Bash? Bash that's available on MacOS is rather dated and @cabreraam's suggestion for #1344 (i.e. to update Bash) should solve this issue. I tested the script locally with Bash 5.0.17.

**Comment by jeffhammond** [comment]
Yeah, I installed bash via homebrew to workaround this.  It's a low impact issue.

**Comment by banach-space** [comment]
This change will make `flang` generate an error if your version of Bash is too old: https://reviews.llvm.org/D116608. 

Btw, thanks for flagging this up!

**Comment by banach-space** [comment]
Closing this as I don't expect any other updates beyond https://reviews.llvm.org/D116608.

**Comment by banach-space** [comment]
Closing this as I don't expect any other updates beyond https://reviews.llvm.org/D116608.
