### ISSUE TITLE
fm020 undefined reference to `_QPifon01'

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#135]
flang fm020.o     -o fm020.out
fm020.o: In function `_QQmain'
fcvs/src/fm020.f:152: undefined reference to `_QPifon01'

**Comment by jeanPerier** [comment]
I think this one may be a rather be a lowering problem, statement function are not yet lowered.
If we want to handle them as mlir function (as opposed to directly in-lining them in the bridge)
- `StmtFunctionStmt` needs to be handled in the PFT as functionLike unit.
- The some care may have to be taken in the bridge around startNewFunction given the structure of statement function is different.
- The internal mangling needs to reflect the scope and that this is not an external function

Directly in-lining it in the bridge would require some care to correctly map the argument symbols with actual arguments but is also an option.

**Comment by schweitzpgi** [comment]
#153
