### ISSUE TITLE
EQUIVALENCE on globals is not implemented (fm502)

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#136]
flang fm024.o     -o fm024.out
./fm024.out > fm024.log
IEEE arithmetic exceptions signaled: INEXACT diff fm024.log 
       650       FAIL              -1          32767

**Comment by jeanPerier** [comment]
This tests EQUIVALENCE statement. EQUIVALENCE statement is not handled, but it should at least die at compile time with a clear message that this is not supported yet.

**Comment by schweitzpgi** [comment]
fm025 compiles for me

**Comment by sscalpone** [comment]
fm011 fm023 are working
