### ISSUE TITLE
fm050 fm051 fm052 fm055 fm056 fm057 fm058 fm059 COMMON blocks are not implemented

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#137]
Running test fm050
flang fm050.o fm051.o fm052.o fm053.o fm054.o fm055.o     -o fm050.out
./fm050.out > fm050.log
       400       FAIL     0.21654E+01    0.31654E+01

**Comment by jeanPerier** [comment]
Test 400 uses a common block, common blocks are TODO. Again, we should have a compile time die message here until actual support.

**Comment by schweitzpgi** [comment]
PR #256
