### ISSUE TITLE
undefined reference to `__fd_powi_1`, undefined reference to `__mth_i_dsqrt`

### ISSUE THREAD

**Issue by cabreraam** [flang-compiler/f18-llvm-project#1373]
Forgive me if this is a naive question--I don't know a lick of Fortran and am very new to working with `flang-new` and just Fortran in general.

I was trying to compile [this E3SM kernel](https://github.com/E3SM-Project/codesign-kernels/tree/master/atmosphere) and ran into the following error output:

```
$ flang-new -O3  -c biharmonic_wk_kernel.F90
flang-new: warning: argument unused during compilation: '-O3'
flang-new -O3  -o atm biharmonic_wk_kernel.o 
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: biharmonic_wk_kernel.o: in function `_QMkernel_utilsPcompute_l2norm':
/home/93u/Research/flang_stuff/codesign-kernels/atmosphere/./biharmonic_wk_kernel.F90:72: undefined reference to `__fd_powi_1'
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: /home/93u/Research/flang_stuff/codesign-kernels/atmosphere/./biharmonic_wk_kernel.F90:72: undefined reference to `__fd_powi_1'
/opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: biharmonic_wk_kernel.o: in function `fir.sqrt.f64.f64':
/home/93u/Research/flang_stuff/codesign-kernels/atmosphere/./biharmonic_wk_kernel.F90:580: undefined reference to `__mth_i_dsqrt'
```
I most recently pulled `fir-dev` commit `654837850493cacc4407ebda1cf2b6134138886d`

The offending line of code is here:
```
Line 72: 
l2 = sqrt( sum( (qtens - qtens_save)**2 ) / sum(qtens_save**2) )
```

Is there some library that I need to link against that defines these intrinsic functions (i.e., is there something I'm doing blatantly wrong that will easily fix this?)

Is this problem related to Issue #633?

Any help is appreciated!

**Comment by jeanPerier** [comment]
> Is this problem related to Issue #633?

No, what you are seeing is a libpgmath symbol, it f18 started with it as a default targeted math library, but it can be overridden with the `-math-version=llvm` when compiling "manually" with the `bbc` tool. The `flang-new` driver support in lowering is recent, so I am not sure how to pass such option to it (@banach-space, is it possible to specify `llvm::cl::` flags to `flang-new` ?).

If you have libpgmath around (also available at https://github.com/flang-compiler/flang/tree/master/runtime/libpgmath), you can probably also try to link against it manually.

**Comment by banach-space** [comment]
@jeanPerier Did you mean [-math-runtime](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/lib/Lower/IntrinsicCall.cpp#L892-L900)? 

In general, options for the driver are defined in [Options.td](https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/clang/include/clang/Driver/Options.td) (i.e. through TableGen). It **is** possible to integrate `llvm::cl::` options, but that would require some design work  - we shouldn't just mix different sets of options defined in different places. And if the overlap between `flang-new` and e.g. `bbc` in terms of options is small, then it might be easier to duplicate the definitions (even if the spelling is identical).

For this particular case - is this a fairly standard option? If something similar is available in e.g. Clang or Gfortran then we should try to replicate that (in the spirit of "principle of least surprise"). I couldn't find `--math-runtime` anywhere so I'm guessing it's unique to `bbc`? Also, perhaps this could basically be a linker option? 

@cabreraam Downloading libpgmath and manually adding it to the compiler invocation (`flang-new -lpgmath ...`) might be the easiest and quickest solution for now. If that works for you then I suggest creating a separate ticket/issue for updating `flang-new`.

**Comment by cabreraam** [comment]
I did end up building `libpgmath` from [here](https://github.com/flang-compiler/flang/tree/master/runtime/libpgmath) and successfully linked that library, but I was getting a segfault when running the application that I will look into tomorrow. Thanks for the help @jeanPerier  and @banach-space!

@banach-space, I am happy to create a new issue, but I'm not quite sure what the issue should be titled. I am still very new to `flang` and compilers in general.

**Comment by jeanPerier** [comment]
@banach-space , initially, when there was no driver in lowering, we have used `llvm::cl::` to test some options. My understanding is that we will probably have to move them to something the driver controlled option. The one I am referring to is defined [here](https://github.com/flang-compiler/f18-llvm-project/blob/665463cfac3d15de7c546778698c8695e4e3b4c2/flang/lib/Lower/IntrinsicCall.cpp#L892), and I known that I can drive it from bbc tool with `--math-runtime=llvm`, but it is not clear to me if and how this can be controlled with `flang-new`.

**Comment by Leporacanthicus** [comment]
Segfault when running is quite regularly "running out of stackspace", so try `ulimit -s unlimited` before debugging too much else. This suggestion comes with no guarantees :)

**Comment by kiranchandramohan** [comment]
@jeanPerier is there an option to generate the `math` dialect (https://mlir.llvm.org/docs/Dialects/MathOps/) operations for intrinsics? Or is the preferred approach to always generate `llvm` intrinsics?
Will there be missing intrinsics in llvm?

What is the best approach going forward?
1. Upstream pgmath to the llvm repo.
2. Generate math dialect operations and then convert them to pgmath or llvm intrinsics. Extend the math dialect for this purpose.
3. Generate calls to llvm intrinsics. Add missing intrinsics to llvm. If not possible add to the flang runtime?

**Comment by banach-space** [comment]
> The one I am referring to is defined here, and I known that I can drive it from bbc tool with --math-runtime=llvm.

@jeanPerier That's the same option that I linked :) I was slightly confused as you misspelled it as `--math-version` in your earlier post. All clear - we are referring to the same option. Crisis averted :) 

@cabreraam If you're happy with your current solution then you can close this one and I can create the follow-ups.  Here's one for `--math-runtime=llvm`:  https://github.com/flang-compiler/f18-llvm-project/issues/1377 (@kiranchandramohan shall we move your comment there?). The segfault that you are seeing is likely a separate issue, but please confirm first. Thanks again for testing LLVM Flang!

**Comment by cabreraam** [comment]
@banach-space Perfect. I will go ahead and close this issue. Thanks all for the input!
