### ISSUE TITLE
fcvs/src/fm058.f:37: undefined reference to `_QFfs058Pff059'

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#138]
Running test fm056:
flang fm056.o fm057.o fm058.o fm059.o     -o fm056.out
fcvs/src/fm058.f:37: undefined reference to `_QFfs058Pff059'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeanPerier** [comment]
That is a internal mangling lowering issue. The caller site mangling of external is wrong as it includes the name of the procedure where the call is (as if the extrenal function was an internal procedure).
There is already a FIXME in a test for this.
https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/test/Lower/implicit-interface.f90#L9
It should be an easy fix, I just did not looked into it yet.

**Comment by jeanPerier** [comment]
Fixed by #145
