### ISSUE TITLE
fm252 LLVM ERROR: unexpected character type

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#150]
```
flang -c  fm252.f
LLVM ERROR: unexpected character type
Stack dump:
0.  Program arguments: f18 -module-suffix .f18.mod -intrinsic-module-directory ... -c fm252.f
```

**Comment by zacharyselk** [comment]
[fm252.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm252.f.html)

**Comment by zacharyselk** [comment]
#130

**Comment by schweitzpgi** [comment]
> #130

This one doesn't look like a duplicate. Is that a typo?

**Comment by zacharyselk** [comment]
> > #130
> 
> This one doesn't look like a duplicate. Is that a typo?

The error is coming from lines 116-118 which are:
```
     ASSIGN 0012 TO I                                                  01160252
0012 FORMAT (" **** ASSIGN FORMAT NUMBER TO INTEGER VARIABLE ****" )   01170252
     WRITE (I02, I)                                                    01180252
```

So it is the same issue as #130, though I guess I am not sure if that means it should have the duplicate label or something else.

**Comment by schweitzpgi** [comment]
Thanks for tracking this one down. Closing it for now.
