### ISSUE TITLE
fm020 fm301 fm352 Statement function calls not yet handled in lowering

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#153]
```
flang -c  fm301.f
error: loc("fm301.f":653:7): Statement function calls not yet handled in lowering

```

**Comment by zacharyselk** [comment]
[fm020.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm020.f.html), [fm301.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm301.f.html), & [fm352.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm352.f.html)

**Comment by schweitzpgi** [comment]
This is causing 140 files in LAPACK to fail to compile.

**Comment by schweitzpgi** [comment]
---------------------------------- executing test fm020
./fm020.out > fm020.log
diff fm020.log .//ref/fm020.log
