### ISSUE TITLE
TODO() could offer a descriptive message

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#155]
Right now, the TODO macro prints out a file name and line number.  As the code changes, these values may change, potentially causing duplicate bug reports, which is a burden on the reporter.

Perhaps the macro could be extended with a descriptive message or a unique id.

**Comment by schweitzpgi** [comment]
#133

**Comment by schweitzpgi** [comment]
I'd much rather people spent their time implementing features rather than writing descriptive messages that will be deleted.
