### ISSUE TITLE
fm097 AMAX0 AMIN0 not lowering correctly

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#156]
```
flang -c fm097.f
error: loc("fm097.f":383:7): 'fir.cmpf' op requires all operands to have the same type
llvm ir generation did not succeed
```

**Comment by schweitzpgi** [comment]
fm097 'fir.cmpf' op requires all operands to have the same type

It appears related to the lowering of AMAX0 and AMIN0. The result type does not match the argument types.

**Comment by sscalpone** [comment]
Do we want the front end to insert the proper conversions?

**Comment by schweitzpgi** [comment]
It looks like it may be the algorithm, which is apparently using the return type. For these intrinsics, that won't work.

**Comment by schweitzpgi** [comment]
```
---------------------------------- executing test fm097
./fm097.out > fm097.log
diff fm097.log .//ref/fm097.log
```
