### ISSUE TITLE
fm109 fails

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#158]
flang -c fm109.f
flang fm109.o     -o fm109.out
---------------------------------- executing test fm109
./fm109.out > fm109.log
diff: file - fm109.log:
              -
diff: file - ref/fm109.log:
           -15.
diff: files differ at line 126  ---- test FAIL

**Comment by zacharyselk** [comment]
[fm109.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm109.f.html)

**Comment by klausler** [comment]
Same bug as #146; believed to be fixed.  Please confirm and close.

**Comment by schweitzpgi** [comment]
---------------------------------- executing test fm109
./fm109.out > fm109.log
diff fm109.log .//ref/fm109.log
