### ISSUE TITLE
fm401 ENDFILE not implemented

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#159]
`
fm401.f:374: undefined reference to `_FortranAioBeginEndfile'
`

**Comment by zacharyselk** [comment]
[fm401.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm401.f.html)

**Comment by sscalpone** [comment]
Implemented.
