### ISSUE TITLE
[Driver] Potential driver issue when using `ninja` as generator

### ISSUE THREAD

**Issue by cabreraam** [flang-compiler/f18-llvm-project#1600]
Hi all,

I was trying to build an application using Ninja as the generator. When I tried to compile the project, I hit many errors, but they're all the same. They look like this:

```bash
FAILED: Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90-pp.f90 Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90.o.ddi 
/noback/93u/Research/flang_stuff/f18-llvm-project/build_fir-dev/bin/flang-new -cpp -DNDEBUG  -module-dirFortran/SNAP/src   -w -E /noback/93u/Sandbox/llvm-test-suite/Fortran/SNAP/src/version.f90 > Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90-pp.f90 && /noback/93u/spack/opt/spack/linux-centos7-zen2/gcc-12.1.0/cmake-master-ue3qwcj75ytnmaozqk3delb5drqxstkk/bin/cmake -E cmake_ninja_depends --tdi=Fortran/SNAP/src/CMakeFiles/snap.dir/FortranDependInfo.json --lang=Fortran --pp=Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90-pp.f90 --dep=Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90-pp.f90.d --obj=Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90.o --ddi=Fortran/SNAP/src/CMakeFiles/snap.dir/version.f90.o.ddi
flang-new: error: unknown argument: '-module-dirFortran/SNAP/src'
```

The last line, 
```bash
flang-new: error: unknown argument: '-module-dirFortran/SNAP/src'
```

makes me think that there is a missing space somewhere in the driver? When I insert the space s.t. the command becomes `... -module-dir Fortran/SNAP/src`, the compilation succeeds. Additionally, I've tested with Make as the generator with no issues.

For context, I'm using CMake that has flang support, I'm in the `fir-dev` branch, and I'm using `flang-new`.

@banach-space, is this something that you could investigate?

Thanks,
Anthony

**Comment by banach-space** [comment]
This was fixed in  https://reviews.llvm.org/D125957, which is missing from `fir-dev` :)  Why not switch to upstream llvm-project instead?

-Andrzej

**Comment by cabreraam** [comment]
Because I didn't know I could do that! Thanks for the heads up. Once I test it, I'll close this.

Thanks @banach-space !

**Comment by cabreraam** [comment]
Okay, I was able to use `flang-new` from the upstream llvm repo to successfully build `SNAP`. However, I did encounter the following error during the CMake configure step:

```bash
  The Fortran compiler

    "/noback/93u/Research/flang_stuff/llvm-project/build_main/bin/flang-new"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /noback/93u/Sandbox/llvm-test-suite/build_upstream_llvm/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/auto/software/utilities/x86_64/ninja/1.10.2.git/bin/ninja cmTC_76791 && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_76791.dir/testFortranCompiler.f-pp.f
    [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_76791.dir/Fortran.dd
    [3/4] Building Fortran object CMakeFiles/cmTC_76791.dir/testFortranCompiler.f.o
    [4/4] Linking Fortran executable cmTC_76791
    FAILED: cmTC_76791 
    : && /noback/93u/Research/flang_stuff/llvm-project/build_main/bin/flang-new   CMakeFiles/cmTC_76791.dir/testFortranCompiler.f.o -o cmTC_76791   && :
    /usr/bin/ld: cannot find -lFortran_main
    /usr/bin/ld: cannot find -lFortranRuntime
    /usr/bin/ld: cannot find -lFortranDecimal
```

The last bit is the problem:
```bash
    /usr/bin/ld: cannot find -lFortran_main
    /usr/bin/ld: cannot find -lFortranRuntime
    /usr/bin/ld: cannot find -lFortranDecimal
```
I tried to install `lld` in the same project as my upstream flang-new build, but for some reason I couldn't get it to build when I specified `lld` as an additional option in `LLVM_ENABLE_PROJECTS` as shown here:

```bash
-DLLVM_ENABLE_PROJECTS=mlir;flang;clang;lld
```.

 What I ended up doing is just passing the option
```bash
-DCMAKE_Fortran_FLAGS="-L/path/to/flang/build/lib"
```
which is where the libraries live. If I were to use the `lld` associated with my upstream llvm project flang build, would the linker know by default where those libraries are?

The high order bit, though, is that this successfully builds using `flang-new` in the upstream llvm project!


However, when I pass

**Comment by banach-space** [comment]
Great news!

The missing search path is added in [Gnu.cpp](https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Gnu.cpp#L600), so you shouldn’t require the extra CMake flag when configuring SNAP. How did you run CMake? Did you follow the [docs](https://github.com/llvm/llvm-project/blob/main/flang/docs/FlangDriver.md#cmake-support)? 

Thanks!

**Comment by cabreraam** [comment]
Ah, based on the [docs](https://github.com/llvm/llvm-project/blob/main/flang/docs/FlangDriver.md#cmake-support), __I was not passing `-flang-experimental-exec`__. That solved my linking issue! Thanks @banach-space!
