### ISSUE TITLE
[X86] flang doesn't generate loop vectorization instructions for basic array initialization

### ISSUE THREAD

**Issue by vfdff** [flang-compiler/f18-llvm-project#1602]
For a basic 3D array initialization, flang does not generate loop vectorization instructions, while ifort done.

test case, see detail in https://godbolt.org/z/rPo5WaEoq
```
program small
  implicit none
  integer, parameter :: ADM_gall = 1156
  integer, parameter :: ADM_kall = 42
  integer, parameter :: ADM_lall = 2
  integer, parameter :: ADM_gall_pl = 6 
  integer, parameter :: ADM_lall_pl = 2
 
  real(8) :: rhogvx   (ADM_gall,   ADM_kall,ADM_lall   ) ! rho*Vx ( gam2 X G^{1/2} )
  real(8) :: rhogvx_pl(ADM_gall_pl,ADM_kall,ADM_lall_pl)
 
  rhogvx=2
  !rhogvx_pl=2

  call src_flux_convergence(rhogvx, rhogvx_pl)
endprogram small
```

**Comment by jeanPerier** [comment]
Hi, thanks for the report. Please note that we moved to LLVM issues for flang now that it is fully upstreamed. We have not migrated the issues so this is still open, but new issues should be opened there.

@banach-space, if I copy past the LLVM IR produced by `flang-new -O3 -g -w -S -emit-llvm` and pass it to `-O3 -g -w -S`, I get vectorized code. Is something missing in the driver pipeline to allow vectorization at -O3 ?

**Comment by jeanPerier** [comment]
https://godbolt.org/z/xG7vGnsvY

**Comment by banach-space** [comment]
Thanks for reporting this and for the reproducers! And sorry for the delay, I had a bit of catching up to do last week.

@jeanPerier Both Clang and Flang use default set-ups from LLVM for their optimisation pipelines. However, there's also a great deal of fine-tuning in Clang, which has not been considered in Flang.  The following experiment should provide a hint (run on AArch64):
```
$ bin/clang -Xclang -fdebug-pass-manager -O3 -g -w -S file.ll 2>&1 | wc -l
355
$ bin/flang-new -Xflang -fdebug-pass-manager -O3 -g -w -S file.ll 2>&1 | wc -l
330
```

Once the missing vectorizer pass is identified, one could enable it in Flang. We just need a volunteer to find it and to send a patch :) (happy to review it!)

@vfdff I suggest moving this issue to https://github.com/llvm/llvm-project/issues

**Comment by kiranchandramohan** [comment]
I see vector instructions from a recent build. Closing this.
