### ISSUE TITLE
fm200 - parser chokes on a line continuation

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#161]

**Comment by zacharyselk** [comment]
[fm200.f](https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm200.f.html)

**Comment by klausler** [comment]
Works for me with `f18 -funparse fm200.f`; what did you observe?

**Comment by schweitzpgi** [comment]
% `f18 -funparse src/fm200.f`
src/fm200.f:468:6: error: obsolete legacy extension is not supported
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'NAMELIST'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DATA'
   0132
       ^
src/fm200.f:468:6: in the context: DATA statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ENTRY'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORMAT'
   0132
       ^
src/fm200.f:468:6: in the context: FORMAT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORALL'
   0132
       ^
src/fm200.f:468:6: in the context: FORALL construct statement
src/fm200.f:468:2: in the context: FORALL construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WHERE'
   0132
       ^
src/fm200.f:468:6: in the context: WHERE construct statement
src/fm200.f:468:2: in the context: WHERE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT TYPE ('
   0132
       ^
src/fm200.f:468:6: in the context: SELECT TYPE statement
src/fm200.f:468:2: in the context: SELECT TYPE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT RANK'
   0132
       ^
src/fm200.f:468:6: in the context: SELECT RANK statement
src/fm200.f:468:2: in the context: SELECT RANK construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:2: in the context: IF construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CRITICAL'
   0132
       ^
src/fm200.f:468:6: in the context: CRITICAL statement
src/fm200.f:468:2: in the context: CRITICAL construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CHANGE TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: CHANGE TEAM statement
src/fm200.f:468:2: in the context: CHANGE TEAM construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT CASE'
   0132
       ^
src/fm200.f:468:6: in the context: SELECT CASE statement
src/fm200.f:468:2: in the context: SELECT CASE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'BLOCK'
   0132
       ^
src/fm200.f:468:2: in the context: BLOCK construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ASSOCIATE'
   0132
       ^
src/fm200.f:468:6: in the context: ASSOCIATE statement
src/fm200.f:468:2: in the context: ASSOCIATE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'PAUSE'
   0132
       ^
src/fm200.f:468:6: in the context: PAUSE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: assigned GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ASSIGN'
   0132
       ^
src/fm200.f:468:6: in the context: ASSIGN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:6: in the context: arithmetic IF statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORALL'
   0132
       ^
src/fm200.f:468:6: in the context: FORALL statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: computed GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE'
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE ('
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE ('
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WHERE'
   0132
       ^
src/fm200.f:468:6: in the context: WHERE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WAIT'
   0132
       ^
src/fm200.f:468:6: in the context: WAIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'UNLOCK ('
   0132
       ^
src/fm200.f:468:6: in the context: UNLOCK statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC TEAM statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC MEMORY'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC MEMORY statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC IMAGES'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC IMAGES statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC ALL'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC ALL statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ERROR STOP'
   0132
       ^
src/fm200.f:468:6: in the context: STOP statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'STOP'
   0132
       ^
src/fm200.f:468:6: in the context: STOP statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'REWIND'
   0132
       ^
src/fm200.f:468:6: in the context: REWIND statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'RETURN'
   0132
       ^
src/fm200.f:468:6: in the context: RETURN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ'
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ'
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ ('
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ ('
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'PRINT'
   0132
       ^
src/fm200.f:468:6: in the context: PRINT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'OPEN ('
   0132
       ^
src/fm200.f:468:6: in the context: OPEN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'NULLIFY'
   0132
       ^
src/fm200.f:468:6: in the context: NULLIFY statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'LOCK ('
   0132
       ^
src/fm200.f:468:6: in the context: LOCK statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'INQUIRE'
   0132
       ^
src/fm200.f:468:6: in the context: INQUIRE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:6: in the context: IF statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORM TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: FORM TEAM statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FLUSH'
   0132
       ^
src/fm200.f:468:6: in the context: FLUSH statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FAIL IMAGE'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EXIT'
   0132
       ^
src/fm200.f:468:6: in the context: EXIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EVENT WAIT'
   0132
       ^
src/fm200.f:468:6: in the context: EVENT WAIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EVENT POST'
   0132
       ^
src/fm200.f:468:6: in the context: EVENT POST statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ENDFILE'
   0132
       ^
src/fm200.f:468:6: in the context: ENDFILE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DEALLOCATE ('
   0132
       ^
src/fm200.f:468:6: in the context: DEALLOCATE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CYCLE'
   0132
       ^
src/fm200.f:468:6: in the context: CYCLE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CONTINUE'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CLOSE'
   0132
       ^
src/fm200.f:468:6: in the context: CLOSE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CALL'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'BACKSPACE'
   0132
       ^
src/fm200.f:468:6: in the context: BACKSPACE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ALLOCATE ('
   0132
       ^
src/fm200.f:468:6: in the context: ALLOCATE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DO'
   0132
       ^
src/fm200.f:468:6: in the context: nonlabel DO statement
src/fm200.f:468:2: in the context: DO construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'END DO'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DO'
   0132
       ^
src/fm200.f:468:6: in the context: label DO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
f18 -funparse src/fm200.f
src/fm200.f:468:6: error: obsolete legacy extension is not supported
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'NAMELIST'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DATA'
   0132
       ^
src/fm200.f:468:6: in the context: DATA statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ENTRY'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORMAT'
   0132
       ^
src/fm200.f:468:6: in the context: FORMAT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORALL'
   0132
       ^
src/fm200.f:468:6: in the context: FORALL construct statement
src/fm200.f:468:2: in the context: FORALL construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WHERE'
   0132
       ^
src/fm200.f:468:6: in the context: WHERE construct statement
src/fm200.f:468:2: in the context: WHERE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT TYPE ('
   0132
       ^
src/fm200.f:468:6: in the context: SELECT TYPE statement
src/fm200.f:468:2: in the context: SELECT TYPE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT RANK'
   0132
       ^
src/fm200.f:468:6: in the context: SELECT RANK statement
src/fm200.f:468:2: in the context: SELECT RANK construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:2: in the context: IF construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CRITICAL'
   0132
       ^
src/fm200.f:468:6: in the context: CRITICAL statement
src/fm200.f:468:2: in the context: CRITICAL construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CHANGE TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: CHANGE TEAM statement
src/fm200.f:468:2: in the context: CHANGE TEAM construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SELECT CASE'
   0132
       ^
src/fm200.f:468:6: in the context: SELECT CASE statement
src/fm200.f:468:2: in the context: SELECT CASE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'BLOCK'
   0132
       ^
src/fm200.f:468:2: in the context: BLOCK construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ASSOCIATE'
   0132
       ^
src/fm200.f:468:6: in the context: ASSOCIATE statement
src/fm200.f:468:2: in the context: ASSOCIATE construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'PAUSE'
   0132
       ^
src/fm200.f:468:6: in the context: PAUSE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: assigned GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ASSIGN'
   0132
       ^
src/fm200.f:468:6: in the context: ASSIGN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:6: in the context: arithmetic IF statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORALL'
   0132
       ^
src/fm200.f:468:6: in the context: FORALL statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: computed GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE'
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE ('
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WRITE ('
   0132
       ^
src/fm200.f:468:6: in the context: WRITE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WHERE'
   0132
       ^
src/fm200.f:468:6: in the context: WHERE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'WAIT'
   0132
       ^
src/fm200.f:468:6: in the context: WAIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'UNLOCK ('
   0132
       ^
src/fm200.f:468:6: in the context: UNLOCK statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC TEAM statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC MEMORY'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC MEMORY statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC IMAGES'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC IMAGES statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'SYNC ALL'
   0132
       ^
src/fm200.f:468:6: in the context: SYNC ALL statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ERROR STOP'
   0132
       ^
src/fm200.f:468:6: in the context: STOP statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'STOP'
   0132
       ^
src/fm200.f:468:6: in the context: STOP statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'REWIND'
   0132
       ^
src/fm200.f:468:6: in the context: REWIND statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'RETURN'
   0132
       ^
src/fm200.f:468:6: in the context: RETURN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ'
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ'
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ ('
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'READ ('
   0132
       ^
src/fm200.f:468:6: in the context: READ statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'PRINT'
   0132
       ^
src/fm200.f:468:6: in the context: PRINT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'OPEN ('
   0132
       ^
src/fm200.f:468:6: in the context: OPEN statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'NULLIFY'
   0132
       ^
src/fm200.f:468:6: in the context: NULLIFY statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'LOCK ('
   0132
       ^
src/fm200.f:468:6: in the context: LOCK statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'INQUIRE'
   0132
       ^
src/fm200.f:468:6: in the context: INQUIRE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'IF'
   0132
       ^
src/fm200.f:468:6: in the context: IF statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'GO TO'
   0132
       ^
src/fm200.f:468:6: in the context: GOTO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FORM TEAM'
   0132
       ^
src/fm200.f:468:6: in the context: FORM TEAM statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FLUSH'
   0132
       ^
src/fm200.f:468:6: in the context: FLUSH statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'FAIL IMAGE'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EXIT'
   0132
       ^
src/fm200.f:468:6: in the context: EXIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EVENT WAIT'
   0132
       ^
src/fm200.f:468:6: in the context: EVENT WAIT statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'EVENT POST'
   0132
       ^
src/fm200.f:468:6: in the context: EVENT POST statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ENDFILE'
   0132
       ^
src/fm200.f:468:6: in the context: ENDFILE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DEALLOCATE ('
   0132
       ^
src/fm200.f:468:6: in the context: DEALLOCATE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CYCLE'
   0132
       ^
src/fm200.f:468:6: in the context: CYCLE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CONTINUE'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CLOSE'
   0132
       ^
src/fm200.f:468:6: in the context: CLOSE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'CALL'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'BACKSPACE'
   0132
       ^
src/fm200.f:468:6: in the context: BACKSPACE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'ALLOCATE ('
   0132
       ^
src/fm200.f:468:6: in the context: ALLOCATE statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DO'
   0132
       ^
src/fm200.f:468:6: in the context: nonlabel DO statement
src/fm200.f:468:2: in the context: DO construct
   0132
   ^
src/fm200.f:468:2: in the context: execution part construct
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'END DO'
   0132
       ^
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
src/fm200.f:468:6: error: expected 'DO'
   0132
       ^
src/fm200.f:468:6: in the context: label DO statement
src/fm200.f:468:2: in the context: execution part construct
   0132
   ^
in the context: execution part
in the context: main program
f18: could not parse src/fm200.f

**Comment by klausler** [comment]
Please message me a link to the source file that you're compiling; I don't think that it's the same source as the file that I downloaded from the link earlier.

**Comment by klausler** [comment]
Minimal test case:
```
 0132
     1END
```

**Comment by klausler** [comment]
Fixed in f18-stage.

**Comment by klausler** [comment]
Please verify and close if fixed.

**Comment by schweitzpgi** [comment]
```
---------------------------------- executing test fm200
./fm200.out > fm200.log
diff fm200.log .//ref/fm200.log
```
