### ISSUE TITLE
FORMAT strings should be hashconsed as globals

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#177]
The text of a FORMAT statement is converting into an immediate literal string value rather than hash consed into a global like a CHARACTER literal and then just referenced.

**Comment by Sameeranjoshi** [comment]
Here's some quick analysis :

1. Test of I/O with format statement:
```
program other
       write(6,9010)
9010   format('ok')
end
```

FIR generated:
```
%0 = fir.string_lit "('ok')"(6) : !fir.char<1>
```
`Problem`: It's a quick fix to make it an immediate `literal sting value`.
`expected`: Should have been like `fir.global` and then referenced into code.
for e.g

TEST:
```
CHARACTER(LEN=8), PARAMETER :: J = "Hi there"
```
FIR:
```
%9 = fir.address_of(@_QQcl.4869207468657265) : !fir.ref<!fir.array<8x!fir.char<1>>>
...
fir.global internal @_QECj("Hi there") constant : !fir.array<8x!fir.char<1>>
fir.global @_QQcl.4869207468657265 constant : !fir.array<8x!fir.char<1>> {
  %0 = fir.string_lit "Hi there"(8) : !fir.char<1>
  fir.has_value %0 : !fir.array<8x!fir.char<1>>
}
```
There is other way which doesn't use `fir.string_lit`, but I think above `FIR` is what we expect.

Possible location of problem:
In `Lower/IO.cpp` as test contains a `datatransfer statement` and a `LABEL` this calls `lowerSourceTextAsStringLit` which internally calls
`builder.createStringLit` this generated `immediate `literal sting value``.

Possible fix:
I tried using `builder.createGlobalConstant` in place of `builder.createStringLit` but the parameters mismatch to `materializeCharacter`.

Query:
1. Is there a way we convert from `fir::GlobalOp` to `mlir::Value`?
2. If above isn't possible will returning `fir::AddrOfOp`(addr) and `mlir::ConstantOp`(len) be correct?

Or am I completely wrong here?

**Comment by schweitzpgi** [comment]
Looks like you are on the right track.  When lowering sees a literal CHARACTER, it ends up in this code https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/lib/Lower/ConvertExpr.cpp#L676.

For the FORMAT statement, you'll want to call the same code, but refactor things so you can pass it the FORMAT statement as the content.  (In the expression case, the content is always assumed to be in a front-end expression form.)
