### ISSUE TITLE
array of CHARACTER not lowered by character expression helper (fm908 fm909)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#223]

**Comment by sscalpone** [comment]
`flang/lib/Lower/CharacterExpr.cpp:72: fir::CharBoxValue Fortran::lower::CharacterExprHelper::toDataLengthPair(mlir::Value): Assertion `charBox && "Array unsupported in character lowering helper"'`

**Comment by sscalpone** [comment]
fm711 now working.
