### ISSUE TITLE
fir.coordinate_of' op operand #0 must be any reference or box (fm715)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#225]

**Comment by sscalpone** [comment]
error: loc("/proj/ta/tests/fcvs/src/fm715.f":461:7): 'fir.coordinate_of' op operand #0 must be any reference or box, but got '!fir.array<6x!fir.char<1>>'

**Comment by schweitzpgi** [comment]
closing as fm715.f has a different failure mode now.
