### ISSUE TITLE
"CHARACTER variable must have LEN parameter" explicit interface runs into a TODO (fm717)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#226]

**Comment by sscalpone** [comment]
`f18: /local/home/sjs/mirror/fir-dev-mirror/flang/lib/Lower/Bridge.cpp:1980: void {anonymous}::FirConverter::mapSymbolAttributes(const Fortran::lower::pft::Variable&, llvm::DenseMap<long unsigned int, mlir::Value>&, mlir::Value): Assertion `e && "CHARACTER variable must have LEN parameter"' failed`
