### ISSUE TITLE
fm805 dprod intrinsic is not implemented

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#227]
https://sourceryinstitute.github.io/RefactorF4Acc-test-docs/tests/NIST_F78_test_suite/fcvs21_f95/doc/sourcefile/fm805.f.html

**Comment by jeanPerier** [comment]
One must just define and implement a `genDprod` `ElementalGenerator`  in https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/lib/Lower/IntrinsicCall.cpp
See `genDim` for an example of how to do that.

**Comment by schweitzpgi** [comment]
@AlexisPerry looking at this
