### ISSUE TITLE
Expression Analysis Folding Replaces Inquiries With Non Constant Expressions

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18-llvm-project#230]
If a symbol X property P depends on symbol N in the declaration parts, evaluate folding may replace inquiry P(X) by a reference to symbol N. That is wrong because the value of N may be modified between its use in the declaration part related to X and the appearance of P(X) in the execution parts.

Example:
```
integer function ifoo(n)
  integer :: n
  character(n) :: c
  n = n+32
  ifoo = len(c)
end function

  integer :: n
  n = 10
  print *, ifoo(n)
end
```

When compiled with f18 + fortran compier (e.g. gfortran) prints 42 instead of the expected 10.
This is because `ifoo` is rewritten to (f18 -funparse):
```
INTEGER FUNCTION ifoo(n)
 INTEGER n
 CHARACTER(LEN=n) c
  n=n+32_4
  ifoo=int(int(n,kind=8),kind=4)
END FUNCTION
```
In this case, `len(c)` was rewritten  to `int(int(n,kind=8),kind=4)` which is not correct since `n` may change after its usage on function entry to define c length.
I did not test but the same issue may appear with other inquiries (ubound, lbound, ...).
I think the fix could be to prevent the rewrite of the inquiry to the expression from the symbol map if the expression is not constant.

**Comment by klausler** [comment]
Fix is in llvm-project/master.

**Comment by sscalpone** [comment]
Fixed in fir-dev.
