### ISSUE TITLE
Fix test/Semantics/label01.F90 so it stops reporting failure

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#234]
This test looks like it started to report failure after a rebase and changes to the test infra.

**Comment by schweitzpgi** [comment]
Looks like https://reviews.llvm.org/D83007 is related.

**Comment by schweitzpgi** [comment]
Testing Time: 22.74s
  Passed: 440
[100%] Built target check-flang

**Comment by tskeith** [comment]
The test was checking that "error: " didn't appear in the output. But that was erroneously matching a warning that ends "would be in error:". So it was changed to check for ": error: " instead.
