### ISSUE TITLE
 Fortran runtime error: Not an open I/O unit number: 7 (fm401)

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#243]
```
flang -c   /proj/ta/tests/fcvs/src/fm401.f
warning: overriding the module target triple with x86_64-unknown-linux-gnu [-Woverride-module]
1 warning generated.
flang fm401.o     -o fm401.out
---------------------------------- executing test fm401
./fm401.out > fm401.log

fatal Fortran runtime error: Not an open I/O unit number: 7
Aborted
```

**Comment by klausler** [comment]
I may have to figure out first why you didn't get original source file and line number information in that runtime error message, so that we can then figure out which statement in the test is the one that failed.

**Comment by klausler** [comment]
Fix out for review in f18-stage.

**Comment by klausler** [comment]
Fixed; will push patch downstream to llvm.

**Comment by klausler** [comment]
Fixed in llvm-project/master.

**Comment by sscalpone** [comment]
Same test, now getting:
`fatal Fortran runtime error: WRITE(UNIT=7) with ACTION='READ'`

**Comment by klausler** [comment]
That test (fm401) seems to have further problems; will fix.

**Comment by sscalpone** [comment]
Verified
