### ISSUE TITLE
CHARACTER without format statement in IO not handled.

### ISSUE THREAD

**Issue by Sameeranjoshi** [flang-compiler/f18-llvm-project#253]
Test for read/write without using a format statement fails .
```
program some
 character buffer(255)
  character greeting(255)
  write (buffer) "sameeran"
  read (buffer) greeting
end
```
I see 
```
input for entity type '!fir.array<1x255x!fir.char<1>>' not implemented
```
with a stack trace.

**Comment by schweitzpgi** [comment]
If we decode that type, it is an array of 255 CHARACTERs with LEN 1.  At this time, only scalars are handled.

```fortran
CHARACTER(len=255) buffer
```
gives us a scalar.

**Comment by schweitzpgi** [comment]
How is this different than #204 ?

**Comment by Sameeranjoshi** [comment]
In #204 jean mentions in description error as `incorrect FIR, error: 'std.call' op incorrect number of operands for callee` 
But yes it's a duplicate with different errors I guess.

**Comment by sscalpone** [comment]
I just changed the title without really checking that it's true.

**Comment by schweitzpgi** [comment]
closing since it is marked a dup.
