### ISSUE TITLE
fir.extract_value incorrectly formed running aggregate.fir

### ISSUE THREAD

**Issue by Sameeranjoshi** [flang-compiler/f18-llvm-project#278]
Running 
```
./bin/tco  ../flang/not-test/fir/aggregate.fir
```
executes UNREACHABLE code from below 
https://github.com/flang-compiler/f18-llvm-project/blob/43b63dbb25e63081fd2dfa6517539d539549ba45/flang/lib/Optimizer/CodeGen/CodeGen.cpp#L1587

**Comment by schweitzpgi** [comment]
This is a TODO item. You can comment out the second function.
