### ISSUE TITLE
alternate return assertion failure (fm510)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#303]

**Comment by vdonaldson** [comment]
There were a handful of problems with alternate entry points, alternate returns, and alternate entry points with alternate returns.  Those have been addressed.

This file is part of multi-file test fm{509,510,511,512,513}.f.  There is a problem involving character arrays in fm512.f that is expected to be addressed elsewhere.  The remaining subtests in this test now compile and execute correctly.

Test fm{517,518,519}.f also has alternate points, and now executes correctly.
