### ISSUE TITLE
global instantiation failed (fm715)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#304]

**Comment by sscalpone** [comment]
`flang/lib/Lower/Bridge.cpp:1711: void {anonymous}::FirConverter::instantiateGlobal(const Fortran::lower::pft::Variable&): Assertion `c.hasValue()' failed.`

**Comment by sscalpone** [comment]
Now:
`f18: /local/home/sjs/mirror/fir-dev-mirror/flang/lib/Lower/Bridge.cpp:1980: void {anonymous}::FirConverter::mapSymbolAttributes(const Fortran::lower::pft::Variable&, llvm::DenseMap<long unsigned int, mlir::Value>&, mlir::Value): Assertion `e && "CHARACTER variable must have LEN parameter"' failed.`
