### ISSUE TITLE
unknown edit descriptor (fm405)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#334]
fatal Fortran runtime error(.//src/fm405.f:389): Unknown 'PF' edit descriptor in FORMAT

**Comment by sscalpone** [comment]
Fix is upstream:
https://github.com/llvm/llvm-project/commit/e57464151d4c4912a7ec4d6fd0920056b2f75c7c#diff-7a396545d32c3d99047c31e87fac6e25

[flang] Allow omission of comma in FORMAT(1PE5.2) in runtime

A comma is not required between a scale factor and a following
data edit descriptor (C1302).

Reviewed By: PeteSteinfeld

Differential Revision: https://reviews.llvm.org/D84369

**Comment by schweitzpgi** [comment]
Will pick this up on next rebase, then can close.
