### ISSUE TITLE
error open unit (fm411)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#335]
```
fatal Fortran runtime error(.//src/fm411.f:250): Not an open I/O unit number: 8
```

**Comment by sscalpone** [comment]
Now getting:
`fatal Fortran runtime error(/proj/ta/tests/fcvs/src/fm411.f:782): Attempt to write 24 bytes to position 316 in a fixed-size record of 336 bytes`
