### ISSUE TITLE
FILE= required (fm413)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#336]
```
fatal Fortran runtime error(.//src/fm413.f:263): FILE= is required unless STATUS='OLD' and unit is connected
```

**Comment by sscalpone** [comment]
New error 
fatal Fortran runtime error(/proj/ta/tests/fcvs/src/fm413.f:288): Attempt to write 24 bytes to position 72 in a fixed-size record of 80 bytes
