### ISSUE TITLE
PFTBuilder Assertion `!evaluationListStack.empty() && "empty evaluation list stack"' failed (aermod)

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#348]
aermod from the polyhedron 04 suite
```
flang -I/proj/ta/tests/polyhedron_05    -I/proj/ta/tests/polyhedron_05 -o aermod aermod.f90
f18: flang/lib/Lower/PFTBuilder.cpp:288: Fortran::lower::pft::Evaluation& {anonymous}::PFTBuilder::addEvaluation(Fortran::lower::pft::Evaluation&&): Assertion `!evaluationListStack.empty() && "empty evaluation list stack"' failed.
```

**Comment by Sameeranjoshi** [comment]
I tried `debug_build/bin/flang   /tmp/pb11/lin/source/aermod.f90` things work for me.
My fir-dev HEAD is at `c66dfb1c52758ad1e65a32bd62c0bc07c1e9a4b5`

**Comment by sscalpone** [comment]
Still fails for me with the same assertion in fir-dev.

@Sameeranjoshi Did you try bbc on the unparsed output?

**Comment by vdonaldson** [comment]
The bridge can't handle module data statements, such as -

```
  module m
    data n /1/
  end
```

Bridge code has been updated to avoid this crash.  Several other small steps have also been taken toward compilation of post f77 code without implementing this feature or making other major changes.  Compilation of aermod.f90 will now hit an assert when encountering an interface declaration.
