### ISSUE TITLE
Is a directive a declaration?

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#363]
From NASTRAN-95/mis/partn3.f
```
% cat c.f
CDIR$ INTEGER
      IMPLICIT INTEGER (A-Z)
      END
% flang c.f
c.f:2:29: error: IMPLICIT statements must follow USE and IMPORT and precede all other declarations
        IMPLICIT INTEGER (A-Z)
                              ^
c.f:2:7: in the context: declaration construct
        IMPLICIT INTEGER (A-Z)
        ^
c.f:1:1: in the context: specification part
  CDIR$ INTEGER
  ^
c.f:1:1: in the context: main program
```

**Comment by tskeith** [comment]
There is a change in https://reviews.llvm.org/D85693 to allow directive before USE statements and in the implicit part.

There are more places we might want to allow them. For example, the way the grammar is now, in a specification part you have to have OpenACC directives first, then OpenMP, then compiler directives. Also, they can be mixed in among USE statements.

**Comment by schweitzpgi** [comment]
fix should be slurped into fir-dev

**Comment by sscalpone** [comment]
Fixed.
