### ISSUE TITLE
correctness (fm103 fm108) -- format edit descriptor

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#372]
---------------------------------- executing test fm103
./fm103.out > fm103.log

fatal Fortran runtime error(.//src/fm103.f:165): Data edit descriptor 'A' may not be used with an INTEGER data item
/bin/sh: line 1:  2099 Aborted                 (core dumped) ./fm103.out > fm103.log
make: *** [fm103.run] Error 134

**Comment by schweitzpgi** [comment]
---------------------------------- executing test fm108
./fm108.out > fm108.log

fatal Fortran runtime error(.//src/fm108.f:174): Data edit descriptor 'A' may not be used with an INTEGER data item
/bin/sh: line 1:  2192 Aborted                 (core dumped) ./fm108.out > fm108.log
make: *** [fm108.run] Error 134

**Comment by sscalpone** [comment]
Looks like a case similar to what Peter reported where descriptor bounds are not set correctly.
```
% cat f103a.f
      DIMENSION IADN11(5)
      CHARACTER*1 IADN11
      DATA IADN11/'A', 'B', 'C', 'D', 'E'/
      WRITE ( 6, 77750 ) IADN11
77750 FORMAT ( 5A1 )
      WRITE ( 6, 77751 ) IADN11, 3
77751 FORMAT ( 5A1, I5 )
      END
```
```
% flang f103a.f
rome4: a.out

fatal Fortran runtime error(f103a.f(5a1,i5)ADVANCE:6): Data edit descriptor 'A' may not be used with an INTEGER data item
A
AAborted
```
```
% gfortran f103a.f
% a.out
ABCDE
ABCDE    3
```
