### ISSUE TITLE
correctness (fm107 fm110) -- record length

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#374]
---------------------------------- executing test fm107
./fm107.out > fm107.log

fatal Fortran runtime error(.//src/fm107.f:236): Internal error: RUNTIME_CHECK(recordLength.has_value()) failed at /folk/eschweitz/git/flang-compiler/f18-llvm-project/flang/runtime/unit.cpp(374)
/bin/sh: line 1:  2181 Aborted                 (core dumped) ./fm107.out > fm107.log
make: *** [fm107.run] Error 134
---------------------------------- executing test fm110
./fm110.out < .//input/fm110.in > fm110.log

fatal Fortran runtime error(.//src/fm110.f:486): Internal error: RUNTIME_CHECK(recordLength.has_value()) failed at /folk/eschweitz/git/flang-compiler/f18-llvm-project/flang/runtime/unit.cpp(374)
/bin/sh: line 1:  2211 Aborted                 (core dumped) ./fm110.out < .//input/fm110.in > fm110.log
make: *** [fm110.run] Error 134

**Comment by schweitzpgi** [comment]
#381

**Comment by schweitzpgi** [comment]
Notes:

In fm107, the test writes 27 integers to a file, rewinds the file, and tries to read back an array of 27 integers.

The executable calls `@_FortranAioOutputInteger64` 27 times as expected per loop iteration. The loop runs 31 iterations for a total of 837.
It then calls `@_FortranAioBeginRewind`.
It then crashes inside the first call to `@_FortranAioInputDescriptor`.
The descriptor passed to the failing call describes an array of 27 integers.
```
$15 = (const Fortran::runtime::Descriptor &) @0x7fffffffc6a0: {raw_ = {
    base_addr = 0x7fffffffc6d4, elem_len = 4, version = 20180515, 
    rank = 1 '\001', type = 9 '\t', attribute = 0 '\000', 
    f18Addendum = 0 '\000', dim = {<Fortran::ISO::Fortran_2018::CFI_dim_t> = {
        lower_bound = 0, extent = 27, sm = 4}, <No data fields>}}}
```

**Comment by sscalpone** [comment]
`fatal Fortran runtime error(/proj/ta/tests/fcvs/src/fm107.f:236): Internal error: RUNTIME_CHECK(recordLength.has_value()) failed at /local/home/sjs/mirror/f18-stage/flang/runtime/unit.cpp(374)`

**Comment by sscalpone** [comment]
Fixed.  Verified.
