### ISSUE TITLE
correctness fm111 -- wrong results

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#375]
```
diff fm111.log .//ref/fm111.log
21c21
<            COMPUTED:   1110 2020 .30303E+02   44   55   6.6 70.07 .888E+01   99
---
>            COMPUTED:   1110 2020 .30303E-07   44   55   6.6 70.07 .888E+01   99
27c27
<            COMPUTED:      0   **   **    0   .0E+0   .0   -.4E-2
---
>            COMPUTED:      0   .0   .0    0   .0E+0   .0   -.4E-2
35c35
<            COMPUTED:     5 33.33
---
>            COMPUTED:     6 33.33
make: [fm111.run] Error 1 (ignored)
```

The first mismatch is reading the 10 character input of `"3 3. 3E-1 "` here:
```fortran
        READ(IRVI, 35301)I2I(1,2), IVI, A1S(3), JVI, KVI, A1S(2), AVS,
     1       A1S(1), I2I(1,1)
35301   FORMAT(BZ,(2I4, E10.1, BN, 2I4, F5.2, BZ, F5.2, BN, E10.1))
```

Stepping through this, we get a return value from the read of
```
(gdb) p x
$1 = (float &) @0x7fffffffdadc: 30.3029995
```

However, it appears that the input `"3 3. 3E-1 "` is intended to be interpreted as `"303.03E-10"`, which `.30303e-7`.

The second difference is to be accepted per the test itself.

The third difference (`5` vs. `6`) is due to an implied do loop variable being off-by-one.

**Comment by sscalpone** [comment]
Format bz may not be honoring trailing spaces.

**Comment by klausler** [comment]
Is this bug for https://gitlab-master.nvidia.com/fortran/f18-stage/-/issues/56?  I think the f18 behavior there is correct.

**Comment by sscalpone** [comment]
Now failing with 
```
pgdiff: file - fm111.log:
           COMPUTED:      0   **   **    0   .0E+0   .0   -.4E-2

pgdiff: file - /proj/ta/tests/fcvs/ref/fm111.log:
           COMPUTED:      0   .0   .0    0   .0E+0   .0   -.4E-2

pgdiff: files differ at line 27  ---- test FAILS

```

**Comment by klausler** [comment]
Is this the case described above at the top of this bug report with "The second difference is to be accepted per the test itself."?  Do we know what the value is that's overflowing the field, or is it actually a zero that shouldn't be treated as an output field overflow?

**Comment by schweitzpgi** [comment]
> Is this the case described above at the top of this bug report with "The second difference is to be accepted per the test itself."? Do we know what the value is that's overflowing the field, or is it actually a zero that shouldn't be treated as an output field overflow?

Here is the complete text taken from the source file.
```fortran
C**************************************************************
C!        WRITE(NUVI, 35306) IVI, AVS, A1S(2), JVI, BVS, CVS, CVS
C|  writing -0.0044 as f2.1 was expected to appear as '.0', but if IEEE -0
C!  semantics are preferred, the output will be '**' -- So, just ensure
C|  the value written is not negative
```

**Comment by klausler** [comment]
> > Is this the case described above at the top of this bug report with "The second difference is to be accepted per the test itself."? Do we know what the value is that's overflowing the field, or is it actually a zero that shouldn't be treated as an output field overflow?
> 
> Here is the complete text taken from the source file.
> 
> ```fortran
> C**************************************************************
> C!        WRITE(NUVI, 35306) IVI, AVS, A1S(2), JVI, BVS, CVS, CVS
> C|  writing -0.0044 as f2.1 was expected to appear as '.0', but if IEEE -0
> C!  semantics are preferred, the output will be '**' -- So, just ensure
> C|  the value written is not negative
> ```

We surely want to get IEEE negative zeros correct on input and output, so ** seems right.
