### ISSUE TITLE
 fm908 -- compilation failure

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#388]
```
---------------------------------- executing test fm908
./fm908.out > fm908.log

fatal Fortran runtime error(.//src/fm908.f:204): End of file during input
/bin/sh: line 1:  3875 Aborted                 (core dumped) ./fm908.out > fm908.log
make: *** [fm908.run] Error 134
```

**Comment by sscalpone** [comment]
Peter says:
> Lowering is calling the wrong runtime I/O API (BeginInternalFormattedInput) instead of BeginInternalArrayFormattedInput.

**Comment by AlexisPerry** [comment]
I'm taking a look at this.  Where can I find the specific test that is failing?

**Comment by sscalpone** [comment]
https://www.itl.nist.gov/div897/ctg/fortran_form.htm

**Comment by klausler** [comment]
Be advised, you'll need to figure out how to construct and pass a CHARACTER array descriptor to call BeginInternalArrayFormattedInput().

**Comment by AlexisPerry** [comment]
> https://www.itl.nist.gov/div897/ctg/fortran_form.htm

There's no run script in there, so I tried simply building the fir-dev branch (without modifications) and compiling and running FM908.FOR to try and reproduce the error.  It runs fine and says all the tests pass.  Is there a special run script you are using or a different version of the test suite?

**Comment by sscalpone** [comment]
Did you compile and run it with flang?  Perhaps it used gfortran to compile?

There's an example of linking and running a program in flang/test/Examples/hello.f90.

**Comment by schweitzpgi** [comment]
Merging with #389 -- same issue
