### ISSUE TITLE
correctness fm910 -- bad write position?

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#390]
---------------------------------- executing test fm910
./fm910.out > fm910.log

fatal Fortran runtime error(.//src/fm910.f:161): Attempt to write 24 bytes to position 120 in a fixed-size record of 132 bytes
/bin/sh: line 1:  3895 Aborted                 (core dumped) ./fm910.out > fm910.log
make: *** [fm910.run] Error 134

**Comment by sscalpone** [comment]
May be same issue as #382

**Comment by schweitzpgi** [comment]
Merge with #381
