### ISSUE TITLE
Incorrect Return Values from Functions

### ISSUE THREAD

**Issue by AMD-Chirag** [flang-compiler/f18-llvm-project#422]
Branch: **fir-dev** 

**Problem:**
For any function that is created, the return value is always the function name variable.
For example, for the following code:
```f90
REAL FUNCTION f2()
    REAL::t
    t = 2
END FUNCTION f2
```
(Using the `bbc` tool for codegen.)

**Current:**
It returns `0.0` when called since an intrinsic variable (function name - `f2`) is uninitialized and hence `0`.
This is apparent by looking at the generated IR as well (using `bbc`):
```llvm
llvm.func @_QPf2() -> !llvm.float {
  %0 = llvm.mlir.constant(2.000000e+00 : f32) : !llvm.float
  %1 = llvm.mlir.constant(1 : i64) : !llvm.i64
  %2 = llvm.alloca %1 x !llvm.float {in_type = f32, name = "f2"} : (!llvm.i64) -> !llvm.ptr<float>
  %3 = llvm.mlir.constant(1 : i64) : !llvm.i64
  %4 = llvm.alloca %3 x !llvm.float {in_type = f32, name = "t"} : (!llvm.i64) -> !llvm.ptr<float>
  llvm.store %0, %4 : !llvm.ptr<float>
  %5 = llvm.load %2 : !llvm.ptr<float>
  llvm.return %5 : !llvm.float
}
```

**Expected:**
This behavior is inconsistent with that of `gfortran` where the last expression's variable (from my understanding) is returned.
For this function, returned value using `gfortran` is `2.0`.

**Comment by schweitzpgi** [comment]
Compiling this code with `-Wall`, I get
```
 REAL FUNCTION f2()
                1
Warning: Return value of function ‘f2’ at (1) not set [-Wreturn-type]
```

**Comment by AMD-Chirag** [comment]
Yes, it is apparently, the expected behavior.
However, gfortran still seems to take the last expression as the return value if the function name variable is not assigned any.

For this program:
```fortran
REAL FUNCTION f2()
        REAL :: t, u, v
        t = 4.0
        u = 6.0
        v = t * u
END FUNCTION f2

PROGRAM prog
        WRITE(*, *) "Number is: ", f2()
END PROGRAM prog
```
I get output (when compiled with gfortran) to be:
` Number is:    24.0000000`
Another thing I just noted is that if we pass the the optimize option `-O` (`-O1`, `-Og`, etc. with the exception of `-O0`), the output becomes `0.00000`.

**Comment by tskeith** [comment]
The value returned by f2() is undefined. It could be anything but it's probably whatever value is left in the function return register. Sometimes that happens to be the last expression but often it isn't. I'm sure gfortran isn't guaranteeing anything about what is returned.

**Comment by AMD-Chirag** [comment]
Oh, okay. Thanks for explaining.
I'll close this issue then.
