### ISSUE TITLE
fm701 -- bbc seg fault printing C2D001(2,1:*)

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#433]
Hit this one while triaging fm701 (in fm703.f)
```
% cat cv.f
      SUBROUTINE SN703(C2D001)
      CHARACTER*4 C2D001(2,1:*)
      PRINT *, C2D001
      RETURN
      END
% bbc cv.f
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bbc cv.f
...
Segmentation fault
```

**Comment by schweitzpgi** [comment]
Probably related to #397 TODO?

**Comment by jeanPerier** [comment]
It is not related to #397.
1. I think `PRINT *, C2D001` is illegal Fortran given C2D001 is an assumed size array (No way to know how many elements should be printed). 
Fortran 2018 9.5.2 point 2 : "An assumed-size array (8.5.8.5) is permitted to appear as a whole array in an executable construct or specification expression only as an actual argument in a procedure reference that does not require the shape."
And also C1002 regarding primary expressions : `The designator shall not be a whole assumed-size array.`

So this should probably pass semantics (I am not sure if C1002 is supposed to be enforced already, I only see it mentioned in Semantics/expression.cpp comments.).

2. Now regrading why bbc segfaults without a clear error message:

It looks related to assumed size array handling in lowering.  An empty mlir::Value is created for the last extent of the ExtendedValue of C2D002 when creating the ExtendedValue describing the locals. Later, while lowering the PRINT statement, this ExtendedValue is forwarded to `builder.createShape` that does not expect that some extents might be empty mlir::Value (crash on a value.getType() call).

Trace analysis:
- While adding local variable to the symbol map, am empty mlir::Value created for last extent of the extended value: [Bridge.cpp#L2203](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/Bridge.cpp#L2203)
- Then, while lowering the Print statement, in IO.cpp `genOutputItemList` function:
  - Assumed size array `SymbolRef` expression lowered (ExtendedValue from symbol map returned): [IO.cpp#L248](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/IO.cpp#L248)
  - `builder.createShape` called on resulting extented value: [IO.cpp#L268](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/IO.cpp#L268)
    - `builder.createConvert` called on last extent: [FIRBuilder.cpp#L209](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/FIRBuilder.cpp#L209)
    - `getType()` called on last extent that is an empty value (segfault): [FIRBuilder.cpp#L173](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/FIRBuilder.cpp#L173)


So, given the Fortran standard above, I think  `builder.createShape`  could abort with an error message telling that the shape of assumed-size array cannot be computed.

**Comment by schweitzpgi** [comment]
fm701 runs correctly for me.

**Comment by klausler** [comment]
Fix submitted for review (elsewhere).
