### ISSUE TITLE
tco seg fault printing C2D002(IVD002:IVD003,5:7)

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#434]
Found this triaging fm701 in fm703.f. 
```
% cat cw.f
      SUBROUTINE SN703(IVD002, IVD003, C2D002)
      CHARACTER*4 C2D002(IVD002:IVD003,5:7)
      PRINT *, 'C2D002 ', C2D002
      RETURN
      END
% bbc cw.f
% tco cw.mlir
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: tco cw.mlir
Segmentation fault
```

**Comment by schweitzpgi** [comment]
May be another downstream failures stemming from #397

**Comment by jeanPerier** [comment]
It is not related to #397.
It looks related to assumed size array handling in lowering.  An empty mlir::Value is created for the last extent of the ExtendedValue of C2D002 when creating the ExtendedValue describing the locals. Later, while lowering the PRINT statement, this ExtendedValue is forwarded to `builder.createShape` that does not expect that some extents might be empty mlir::Value (crash on a value.getType() call).

Trace analysis:
- While adding local variable to the symbol map, am empty mlir::Value created for last extent of the extended value: [Bridge.cpp#L2203](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/Bridge.cpp#L2203)
- Then, while lowering the Print statement, in IO.cpp `genOutputItemList` function:
  - Assumed size array `SymbolRef` expression lowered (ExtendedValue from symbol map returned): [IO.cpp#L248](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/IO.cpp#L248)
  - `builder.createShape` called on resulting extented value: [IO.cpp#L268](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/IO.cpp#L268)
    - `builder.createConvert` called on last extent: [FIRBuilder.cpp#L209](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/FIRBuilder.cpp#L209)
    - `getType()` called on last extent that is an empty value (segfault): [FIRBuilder.cpp#L173](https://github.com/flang-compiler/f18-llvm-project/blob/6b389ab58b333612a5d81e868bdf6866d564dee1/flang/lib/Lower/FIRBuilder.cpp#L173)

**Comment by jeanPerier** [comment]
PR #441 is up to fix this. Note that a runtime fix not yet in fir-dev is required to run the compiled program correctly (I did an end-to-end test that was printing weird things, turned out Peter actually fixed the runtime issue 3 days ago).
