### ISSUE TITLE
correctness fm901 -- bad output

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#443]
THIS PROGRAM HAS   4 TESTS

     1    INSPECT                                2 SETS OF 2 COMPUTED LINES     
                                                 EXPECTED                       
                 COMPUTED= 
                          FILW???????35?0??
                          FILW???????35?0??

                          (?.?':
                          (?.?':
                 CORRECT:                        CORRESPONDING LINE(S) MUST MATCH
                          ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
                           =+-*/(),.$':
     2    INSPECT
                 COMPUTED= 
                          ONE THREE FIVE SEVEN NINE ELEVEN
                 CORRECT=  
                          ONE THREE FIVE SEVEN NINE ELEVEN
     3    INSPECT
                 COMPUTED= 
                          YQUARE THE WORLD IN A0 DIGHTS
                 CORRECT=  
                          AROUND THE WORLD IN 80 DAYS  
     4    INSPECT
                 COMPUTED= 
                          TO RXXXX NOT TO EXXX
                 CORRECT=  
                          TO BE OR NOT TO BE

**Comment by jeanPerier** [comment]
Looks related to bad lowering of substring in IO input case. Reproducer:
```
  CHARACTER*4 C
  READ(05, *) C(1:4)
END
```

In the generated fir, the length of C(1:4) passed to the runtime is 1 (instead of 4):
```
  %c1_0 = constant 1 : index
  %9 = fir.convert %c1_0 : (index) -> i64
  %10 = fir.call @_FortranAioInputAscii(%3, %8, %9) : (!fir.ref<i8>, !fir.ref<i8>, i64) -> i1
```
That may be related to substring lowering, but given substring assignment and PRINT*, C(1:4) works as expected, there might be something weird in IO input lowering.

**Comment by schweitzpgi** [comment]
I'd guess this sequence is from the substring op lowering:
```mlir
  %4 = fir.convert %0 : (!fir.ref<!fir.array<4x!fir.char<1>>>) -> !fir.ref<!fir.array<?x!fir.char<1>>>
  %5 = fir.coordinate_of %4, %c0 : (!fir.ref<!fir.array<?x!fir.char<1>>>, index) -> !fir.ref<!fir.char<1>>
```
The `4` is probably getting lost in a conversion from ExtendedValue back to a simple Value.

**Comment by sscalpone** [comment]
Fixed. Verified.
