### ISSUE TITLE
Regression: Lower/OpenMP/omp-parallel-region.f90 consistently fails testing when build uses clang++

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#465]

**Comment by jeanPerier** [comment]
It is most likely due to some missing -DAG in the lit tests (clang++/g++ make different decision in what to evaluate first between `gen(rhs)` and `gen(lhs)`. genAdd(gen(rhs), gen(lhs). Lit tests should never hard code in which order operands must be evaluated since Fortran gives no such guarantee.

**Comment by SouraVX** [comment]
Is it still failing ?
