### ISSUE TITLE
'llvm.call' op result type mismatch: '!llvm.float' != '!llvm.double'

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#490]
Cutdown from polyhedron DODUC.f

```
% cat dd.f
      SUBROUTINE s00013
      IMPLICIT DOUBLE PRECISION(a-h,o-z)
      i = 5
      hj = f00111(i-1)
      END

      DOUBLE PRECISION FUNCTION f00111(i)
      IMPLICIT DOUBLE PRECISION(a-h,o-z)
      COMMON /aaa10/ h(22,2)
      f00111 = h(i,1)
      RETURN
      END
```
```
% flang dd.f
error: loc("dd.f":4:7): 'llvm.call' op result type mismatch: '!llvm.float' != '!llvm.double'
mlir did not succeed
```

**Comment by jeanPerier** [comment]
I strengthen lowering of procedure ref to handle mismatch on result type between callee/caller site due to implicit Fortran rule types (PR: #496) though, as detailed in the PR, maybe crashing like we do now is still the best things to do (I cannot imagine that being a feature people could safely abuse as opposed to argument type mismatch).

In this specific case, I think the type mismatch derivates from a front-end implicit rule bug. Expression `f00111(i-1)` has kind(4) according to the front-end, which I think is not in line with the implicit type rule (we would expect kind(8)).

On the following program:
```
  IMPLICIT DOUBLE PRECISION(a-h,o-z)
  print *, kind(f00())
END
```
gfortran/nvfortran... output: is `8`
Yet, `f18 -funparse -fparse-only` output shows that the kind was evaluated to `4`:
``` 
 IMPLICIT DOUBLE PRECISION(a-h, o-z)
 PRINT *, 4_4
END PROGRAM
```
Symbol resolution also looks wrong `f18 -fdebug-dump-symbols -fparse-only`:
```
Global scope:
  : MainProgram
  f00, EXTERNAL (Function, Implicit): ProcEntity REAL(4)
  MainProgram scope: 
    kind, INTRINSIC (Function): ProcEntity
```

**Comment by schweitzpgi** [comment]
Agreed. f00111 should be implicitly DOUBLE PRECISION, not REAL.

**Comment by sscalpone** [comment]
I am not sure why this example is getting the mismatch message.

```
% cat dd.f
      DOUBLE PRECISION FUNCTION f00113()
      IMPLICIT DOUBLE PRECISION(a-h,o-z)
      eh2o = s00093()
      RETURN
      END

      DOUBLE PRECISION FUNCTION s00093()
      IMPLICIT DOUBLE PRECISION(a-h,o-z)
      s00093 = 2.0
      RETURN
      END
```
```
% flang -c -fdebug-dump-symbols dd.f
Global scope:
  f00113 (Function): Subprogram result:REAL(8) f00113 ()
  s00093 (Function): Subprogram result:REAL(8) s00093 ()
  Subprogram scope: f00113 size=16 alignment=8
    eh2o (Implicit) size=8 offset=8: ObjectEntity type: REAL(8)
    f00113 size=8 offset=0: ObjectEntity funcResult type: REAL(8)
  Subprogram scope: s00093 size=8 alignment=8
    s00093 size=8 offset=0: ObjectEntity funcResult type: REAL(8)
warning: loc("dd.f":3:7): return type mismatches were never standard compliant and may lead to undefined behavior.
```

**Comment by jeanPerier** [comment]
@sscalpone, the warning message still stems from the front-end name resolution bug. The `s00093` symbol you see with `-fdebug-dump-symbols` is not the one that is linked to `s00093` when it is called in `f00113 `. Your symbol with REAL(8) is the one from the definition, not the one resulting from the implicit typing inside `f00113`.

If I slightly modify your example to use the `-funparse-with-symbols` flag (entire output below), you can see that at the reference point, the expressions point to a symbol for `s00093` that has REAL(4) type (`!DEF: /s00093 EXTERNAL (Function, Implicit) ProcEntity REAL(4)`). This symbol is the one we have when lowering the call to `s00093 ` and is wrongly typed by name resolution.

```
!DEF: /f00113 (Function) Subprogram REAL(8)
double precision function f00113()
 implicit double precision(a-h, o-z)
 !DEF: /f00113/eh2 (Implicit) ObjectEntity REAL(8)
 !DEF: /s00093 EXTERNAL (Function, Implicit) ProcEntity REAL(4)
 eh2 = s00093()
 return
end function
!DEF: /s00093 (Function) Subprogram REAL(8)
double precision function s00093()
 implicit double precision(a-h, o-z)
 !DEF: /s00093/s00093 ObjectEntity REAL(8)
 s00093 = 2.0
 return
end function
```

**Comment by sscalpone** [comment]
Peter fixed and bbc is no longer complaining.
