### ISSUE TITLE
Assertion `stmt.typedCall && "Call was not analyzed"' failed.

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#492]
```
% cat ww.f
      INTEGER     N1
      PARAMETER   (N1=16)
      COMPLEX*16  U(N1)
      CALL MATMUL(U,N1)
      END
```
```
%: bbc ww.f |& head
bbc: /local/home/sjs/mirror/fir-dev-mirror/flang/lib/Lower/Bridge.cpp:574: void {anonymous}::FirConverter::genFIR(const Fortran::parser::CallStmt&): Assertion `stmt.typedCall && "Call was not analyzed"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bbc ww.f
 #0 0x0000558cbf4ca50d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/local/home/sjs/mirror/install/bin/bbc+0x340f50d)
 #1 0x0000558cbf4c8244 llvm::sys::RunSignalHandlers() (/local/home/sjs/mirror/install/bin/bbc+0x340d244)
 #2 0x0000558cbf4c83b0 SignalHandler(int) (/local/home/sjs/mirror/install/bin/bbc+0x340d3b0)
 #3 0x000014589efe08a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #4 0x000014589dc4cf47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #5 0x000014589dc4e8b1 abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81:0
```

**Comment by jeanPerier** [comment]
The assert is correct and it the `typedCall` field was not set as indented, so lowering fails.
Is calling MATMUL intrinsic like a subroutine a legal thing though ?

I think the fix is either:
- either the standard allows one to define its own MATMUL subroutine without explicitly giving in an EXTERNAL attribute: `IsIntrinsic` should take a `IntrinsicProcTable::isSubroutine` argument.
- or, The program above is illegal: we should complain that MATMUL cannot be called as a subroutine (not clear to me if the best would be to do so in `IntrinsicProcTable::Probe` or before in semantics.)

Analysis:
The front-end analyzes MATMUL as being an intrinsic, but then the Probe silently fails because `IntrinsicProcTable::Probe` looks for matmul in the subroutine table and it cannot find it (it's a function), so it silently returns nullopt assuming this is a TODO.
We think this is an intrinsic because of the `IntrinsicProcTable::IsIntrinsic` call success here:
https://github.com/llvm/llvm-project/blob/37b2e2b04cf434b368b1edf29609be21952316f9/flang/lib/Semantics/resolve-names.cpp#L5781

**Comment by sscalpone** [comment]
From spec 2k wupwise.  This is more like the original source:

```
% cat ww1.f
      PROGRAM WUPWISE
      IMPLICIT NONE
      INTEGER           N1,N2,N3,N4
      PARAMETER        (N1=16,N2=20,N3=20,N4=20)
      COMPLEX*16        KAPPA
      COMPLEX*16        U(3,3,4,N1,N2,N3,N4)
      COMPLEX*16        AUX(12,N1/2,N2,N3,N4)
      COMPLEX*16        X(12,N1/2,N2,N3,N4)
      COMPLEX*16        P(12,N1/2,N2,N3,N4)

      EXTERNAL MATMUL

      CALL MATMUL(U,N1,N2,N3,N4,KAPPA,X,AUX,P)
      END
```

**Comment by schweitzpgi** [comment]
flang gives a hard error when trying to CALL a user-defined FUNCTION.

```
x.f90:6:8: error: Cannot call function 'ifun' like a subroutine
    call ifun
         ^^^^
x.f90:1:10: Declaration of 'ifun'
  function ifun
           ^^^^
```

**Comment by sscalpone** [comment]
The 2nd example from wuwise is not calling the intrinsic.  The program supplies matmul.

**Comment by jeanPerier** [comment]
Thanks, Steve. I will fix the bugs in name resolution.

If MATMUL appears in an EXTERNAL statement like in your second example, there is no discussion (from 8.5.9 . point 1), that's a name resolution bug.

If it does not appear in EXTERNAL statement, the relevant F2018 standard section on intrinsic name resolution is 19.5.1.4 point 6:
> An intrinsic procedure is established to be intrinsic in a scoping unit if that scoping unit explicitly gives it the INTRINSIC attribute, invokes it as an intrinsic procedure, accesses it from a module, or accesses it from its host where it is established to be intrinsic.

We can argue that calling MATMUL as a subroutine does not count as "invoking it as an intrinsic procedure", so it should not be resolved as an INTRINSIC in name resolution and we also need to fix this.

**Bug digression pushing on the topic of what is "invoking it as an intrinsic procedure"**

We can discuss how far we should push the standard interpretation of what "invoking it as an intrinsic procedure" is.
Exiting compilers disagree on what to decide if you call a function that has an intrinsic name (and did not appear in an EXTERNAL/INTRINSIC statement) with the wrong number/type of argument: some raise an error that the intrinsic is called the wrong way, some assume that it must be an external procedure and compile without warning.

```
What is ACOS ?     | bad intrinsic call       | external with warning |  external no warning | other error |
------------------------------------------------------------------------------------------------------------
print*, ACOS()     | gfortran, nag, xlf, f18  |  ifort                |  nvfortran           |             |
------------------------------------------------------------------------------------------------------------
print*, ACOS(I)    | gfortran, nag, xlf, f18  |  ifort                |  nvfortran           |             |
------------------------------------------------------------------------------------------------------------
print*, ACOS(X=I)  | gfortran, nag, xlf, f18  |  ifort                |                      | nvfortran (keyword on implicit extrenal )|
------------------------------------------------------------------------------------------------------------
print*, ACOS(X, X) | gfortran, nag, xlf, f18  |  ifort                |  nvfortran           |             |
------------------------------------------------------------------------------------------------------------
CALL ACOS(X)       | f18(bug: no error raised)|                       | gfortran, nag, xlf,  |             |
                   |                          |                       | nvfortran, ifort     |             |
------------------------------------------------------------------------------------------------------------
```
Based on these observations, I propose to only change f18 to consider names of intrinsic function in subroutine calls should not
trigger the name to be consider the one of the intrinsic function. And, to keep f18 behaviour in line with xlf, nag, gfortran on the rest.

**Comment by jeanPerier** [comment]
Fixed merged in LLVM: https://reviews.llvm.org/D90049. Will close issue when fir-dev is rebased and tested.

**Comment by sscalpone** [comment]
Verified (this test case).
