### ISSUE TITLE
mlir::BlockArgument: Assertion `*this && "isa<> used on a null type."' failed.

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#504]
```
% cat ls.f
C lawson.f
      subroutine MFEOUT (M, NAMES)
      integer M
      character  NAMES(M)*(*)
      logical      BLKNAM
      BLKNAM = NAMES(1) .eq. ' '
      end
```
```
% bbc ls.f |& head
error: loc("ls.f":6:7): cannot load a variable length char
bbc: /local/home/sjs/mirror/fir-dev-mirror/mlir/include/mlir/IR/Value.h:81: bool mlir::Value::isa() const [with U = mlir::BlockArgument]: Assertion `*this && "isa<> used on a null type."' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bbc ls.f
 #0 0x0000561d4ace1edd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/local/home/sjs/mirror/install/bin/bbc+0x345dedd)
 #1 0x0000561d4acdfc14 llvm::sys::RunSignalHandlers() (/local/home/sjs/mirror/install/bin/bbc+0x345bc14)
 #2 0x0000561d4acdfd80 SignalHandler(int) (/local/home/sjs/mirror/install/bin/bbc+0x345bd80)
 #3 0x00007f604a8608a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #4 0x00007f60494ccf47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
```

**Comment by jeanPerier** [comment]
@schweitzpgi , this is related to the dynamic length character loading in `genLoad`, called from `genExtValue`

https://github.com/flang-compiler/f18-llvm-project/blob/d02a25a4ed03d00c5cea8e6b16c6c73e77dcb4b7/flang/lib/Lower/ConvertExpr.cpp#L283-L289.

What's your idea here regarding `genExtValue` on arrays that should face the same problem ?
Should we:
a. Avoid calling genval/genLoad/genExtValue on value that cannot be represented be loaded.
b. Silently not load in those case and let the consumer deal with this left-over mem ref
c. Make a copy in a temp, to ensure we have the read-only poperty of a value, but return a mem ref like in b.
d. Add a dynamic array value type in fir (like mlir tensor from what I understand from it)  
e. Something else

**Comment by schweitzpgi** [comment]
This code was a pair of crutches and a sling that tried to work around all the various ways CHARACTERs were being lowered. Since we're cleaning all that up now, this part goes in the bit dumpster as well.

We don't need to materialize/load/store/cast/rematerialize CHARACTER expressions any longer, since we can just pass around the pointer and len information. And in the array case, the pointer, len, and shape information.
