### ISSUE TITLE
[FCVS regression] assumed length character parameter lowering fails f715

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18-llvm-project#539]
`error: loc("fm715.f":40:21): 'fir.convert' op invalid type conversion`
Caused by a `fir.array<6xfir.char<kind>>` being casted to `fir.array<?xfir.char<kind>>`.
reproducer:
```
 character(*), parameter :: c = "hello"
 print *, c
end
```

**Comment by schweitzpgi** [comment]
I'm not seeing this any longer.
