### ISSUE TITLE
fir-dev seg faults

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#610]
NVIDIA internal testing of fir-dev shows a few seg faults

- [X] nag_f08_hibiya | u4 | Segmentation fault 
- [X] nag_f08_hibiya | u5 | Segmentation fault 
- [ ] nag_f08_j | jr7 | Segmentation fault
- [X] tonto_05 | test | Segmentation fault

**Comment by jeanPerier** [comment]
Should be fixed by #624 that was merged:
- nag_f08_hibiya | u4 | Segmentation fault
- nag_f08_hibiya | u5 | Segmentation fault
- tonto_05 | test | Segmentation fault


jr7 happens in IO runtime. Still investigating if it is a runtime IO API misuse or an IO runtime issue.

**Comment by sscalpone** [comment]
No more seg fault.  Verified.
