### ISSUE TITLE
F95: intrinsics needed for test framework

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#633]
Test framework needs the following intrinsics.  The functions have been implemented in the runtime.  Note that the list is being tracked in more detail in [this spreadsheet](https://docs.google.com/spreadsheets/d/1ctIPb4ADTuLDgwKzZNCThzNnbOcwWG5tA6UTuA9tO_c/edit?pli=1#gid=1823771597).

This list is for lowering:

- [x] count (@mleair )
- [x] cpu_time (already done by @rovka?)
- [ x] cshift
- [x] dot_product
- [x] ibits
- [x] ishft
- [x] matmul
- [x] modulo
- [x] random_number (@vdonaldson )
- [x] reshape (@mleair)
- [x] size
- [x] spread
- [x] transpose (@kiranchandramohan)
- [x] unpack
- [x] all
- [x] any
- [x] index
- [x] logical
- [x] maxloc
- [x] maxval
- [x] product
- [x] repeat (@kiranchandramohan)
- [x] scan
- [x] spacing
- [x] sum
- [x] transfer
- [x] trim
- [x] verify

```
subroutine c (a)
integer, dimension (:) :: a
integer i
i = size(a)
end subroutine
```
```
% bbc c.f90 |& head
error: loc("./c.f90":4:1): /proj/build/f18/Linux_x86_64/flang/lib/Lower/ConvertExpr.cpp:415: not yet implemented descriptor inquiry other than length
```

**Comment by sscalpone** [comment]
Also: scan, verify, trim

**Comment by jeanPerier** [comment]
DescriptorInquiry (that implements SIZE) waiting for review in #602.

**Comment by jeanPerier** [comment]
- I am currently working on plugging TRIM that already has an API/runtime implementation.
- SCAN, and VERIFY do not have runtime API yet.
- SPACING has no runtime in f18 yet, however, using the [classic flang runtime](https://github.com/flang-compiler/flang/blob/a21454d4a0e27e31743864e389a66b1fd95fbac0/runtime/flang/miscsup_com.c#L4806) would make sense given no descriptors are involved.

**Comment by sscalpone** [comment]
@klausler see above scan, verify, spacing....

**Comment by klausler** [comment]
SCAN, VERIFY, SPACING: will do

**Comment by klausler** [comment]
Are you sure that it's SPACING that you want?  It's not a character intrinsic function.

**Comment by sscalpone** [comment]
Yup, spacing.  This is a collection is intrinsics used in the nag f95 suite.  Here are some more:
index
logical
product
random_number
sum
transfer

**Comment by klausler** [comment]
INDEX is done in the runtime.

**Comment by sscalpone** [comment]
Try Gary's test logvalues.f90 when transfer is implemented.

**Comment by sscalpone** [comment]
Cheating!  I add maxval for lapack.

**Comment by klausler** [comment]
I'm working on the reductions now; SUM is nearly done, and once it's reviewed, the same framework should make short work of the others.

**Comment by klausler** [comment]
SUM and PRODUCT are out for review in f18-stage.

**Comment by jeanPerier** [comment]
LOGICAL done in LLVM (now always folded to another Convert<T>, no ad-hoc lowering needed). Will be "enabled" in fir-dev when rebased.

**Comment by sscalpone** [comment]
Added ANY.

**Comment by klausler** [comment]
https://reviews.llvm.org/D99666 implements ALL, ANY, MAXLOC, MAXVAL, MINLOC, MINVAL, PRODUCT, & SUM.

**Comment by klausler** [comment]
Review for reductions is pending in phabricator; merge request review in f18-stage is pending for EXPONENT, FRACTION, NEAREST, RRSPACING, SCALE, SET_EXPONENT, and SPACING.

**Comment by klausler** [comment]
ALL, ANY, COUNT, MAXLOC, MAXVAL, MINLOC, MINVAL, PRODUCT, and SUM are in llvm-project/main.

**Comment by klausler** [comment]
The APIs, runtime implementations, and unit tests for the numeric intrinsic functions AINT, ANINT, CEILING, EXPONENT, FLOOR, FRACTION, MOD, MODULO, NEAREST, NINT, RRSPACING, SCALE, SET_EXPONENT, & SPACING. are merged into f18-stage; a phabricator review for llvm-project will be out shortly.

**Comment by klausler** [comment]
AINT, ANINT, CEILING, EXPONENT, FLOOR, FRACTION, MOD, MODULO, NEAREST, NINT, RRSPACING, SCALE, SET_EXPONENT, & SPACING are pushed into llvm-project/main;  TRANSFER is out for review in f18-stage.

**Comment by klausler** [comment]
Everything on your list is implemented in the runtime in llvm-project/main except RANDOM_NUMBER.

**Comment by pmccormick** [comment]
Not on the list above but I have the two `adjust`calls, `adjustl()` and `adjustr()`, lowering and passing simple tests (all the way to executable code gen).  Will clean up and add some testing for the lowering and then issue a PR.

**Comment by kiranchandramohan** [comment]
Can I take up the repeat intrinsic lowering?

**Comment by jeanPerier** [comment]
> Can I take up the repeat intrinsic lowering?

Please do, thanks ! I do not know anyone working on lowering for it, the runtime is already there. I added your name in the spreadsheet and in this list.

**Comment by svedan** [comment]
Here is the tracking spreadsheet that we have been using:  
https://docs.google.com/spreadsheets/d/1ctIPb4ADTuLDgwKzZNCThzNnbOcwWG5tA6UTuA9tO_c/edit#gid=1823771597

**Comment by kiranchandramohan** [comment]
Can I take up transpose intrinsic?

**Comment by sscalpone** [comment]
> Can I take up the transpose intrinsic lowering?

Sure!  Thanks

**Comment by svedan** [comment]
Kiran – Please make sure the spreadsheet is updated.

Sam

**Comment by svedan** [comment]
@kiranchandramohan<https://github.com/kiranchandramohan> – Any chance you can pick up Matmul or Dot_product?

**Comment by kiranchandramohan** [comment]
@svedan please assign dot_product to Arm. Andrzej (https://github.com/banach-space) will look into it. We can try Matmul towards the end of next week if no one has started working on it.

**Comment by kiranchandramohan** [comment]
@svedan I can take up matmul if it is not taken already.

**Comment by svedan** [comment]
@kiranchandramohan<https://github.com/kiranchandramohan> – Please go ahead with matmul.

**Comment by kiranchandramohan** [comment]
@svedan dotproduct and matmul lowering were merged this week. Is the intrinsic lowering work now complete?

**Comment by svedan** [comment]
Not yet.  A few intrinsics are being still worked on and this is just for Fortran 95 compliance.  There is a lot more left.  The tracking spreadsheet has several NO’s in the lowering status column.

Sam

**Comment by kiranchandramohan** [comment]
OK. I believe the spreadsheet is not up to date. unpack, cshift etc were implemented by @psteinfeld. I cannot update for MATMUL since I do not have access.

**Comment by svedan** [comment]
@ kiranchandramohan you should have permissions to  edit the spreadsheet.  Let me know if you still cannot.  I am still trying to sort out why the spreadsheet has not been updated with the more recently done intrinsics.

**Comment by psteinfeld** [comment]
It looks like I neglected to update the “Lowering status” column previously for CSHIFT and UNPACK.  This are both done, and I’ve updated the spreadsheet.

Pete

**Comment by sscalpone** [comment]
Verified!   More tracking moved to spreadsheet.
