### ISSUE TITLE
Replace and remove old REAL Ops with builtin Ops

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#657]
The following ops should be replaced by their counterparts in the builtin dialect and then removed.

AddfOp, SubfOp, MulfOp, DivfOp, ModfOp, and CmpfOp.

**Comment by SouraVX** [comment]
Handled these : `AddfOp, SubfOp, MulfOp, DivfOp`.

**Comment by kiranchandramohan** [comment]
@SouraVX Any particular reason you did not take up ModfOp and CmpfOp. I believe the MLIR counterparts are RemFOp and CmpFOp.

**Comment by SouraVX** [comment]
Hi @kiranchandramohan , apologies. I did this patch ~1 month ago, can't recall the exact reason for splitting up :( . I'll check my bandwidth and get back here. Till then removing my assignment from the issue.

**Comment by kiranchandramohan** [comment]
https://github.com/flang-compiler/f18-llvm-project/pull/758 handles ModfOp.

**Comment by schweitzpgi** [comment]
It looks like CmpfOp is the last one standing. Any reason it should not be removed?

**Comment by kiranchandramohan** [comment]
No reason. Have a patch for that. Will create a PR.

**Comment by schweitzpgi** [comment]
I think this work is completed. Closing.
