### ISSUE TITLE
Undefined reference to '_FortranAioOutputReal32'

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#76]
lapack-3.1.0/INSTALL/secondtst.f

`undefined reference to '_FortranAioOutputReal32'`

Code is generated as part of outputing a REAL_4.

**Comment by zacharyselk** [comment]
What commands did you run to get that error?

**Comment by schweitzpgi** [comment]
To reproduce this:
bbc <file> -o - | tco | llc --filetype=obj -

And then link against -lFortranRuntime and -lFortranDecimal with clang++.

**Comment by sscalpone** [comment]
@zacharyselk if you want to fix this up, have a look in
`f18-llvm-project/flang/runtime`
```
% grep Real32 *
io-api.h:bool IONAME(OutputReal32)(Cookie, float);
io-api.h:bool IONAME(InputReal32)(Cookie, float &);
```
Those need to be implemented in `io-api.c`.

**Comment by zacharyselk** [comment]
Alright, I'll take a look at it. 

As a side note, shouldn't we be using fixed width real types instead of `float` and `double` for these functions?

**Comment by klausler** [comment]
> Alright, I'll take a look at it.
> 
> As a side note, shouldn't we be using fixed width real types instead of `float` and `double` for these functions?

If you can find standard fixed-width floating-point types in C++, feel free to change them.
