### ISSUE TITLE
fm411 regression

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#763]
```console
fatal Fortran runtime error(././/src/fm411.f:283): Unformatted output attempted on formatted file
```

Not sure if this is from a change to IO lowering or to the runtime.

**Comment by klausler** [comment]
Thanks; already on it.

**Comment by klausler** [comment]
A review is pending for a fix for this problem in llvm-project/main.

**Comment by klausler** [comment]
This patch is now in llvm-project/main.
