### ISSUE TITLE
Support legacy extension OPEN(ACCESS='APPEND')

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#789]
While I'm trying compile and codegen Xfoil, I encountered

```
/home/ryuta/bin/bbc Xfoil/src/xoper.f
Xfoil/src/xoper.f:3124:50: error: Invalid ACCESS value 'append'
        open(lu,file='dcp.out',status='old',access='append',err=10)
                                                   ^^^^^^^^
/home/ryuta/bin/bbc: semantic errors in ./Xfoil/src/xoper.f
```

This issue is already addressed by https://github.com/flang-compiler/f18-llvm-project/commit/72abc199772c30ea2cffaa5dd4a8aa2bb2b7f18c#diff-bc82e30d81709b26f2c8030300784e95003f1b968e1ed7842fa717858e497336 and https://github.com/flang-compiler/f18-llvm-project/commit/8cd199b85f907a7349bc5cb1b3d3562e0e79b72c#diff-bc82e30d81709b26f2c8030300784e95003f1b968e1ed7842fa717858e497336 in `main`.

Can this fix be pushed to `fir-dev` as well?

**Comment by jeanPerier** [comment]
It has been a while fir-dev was not rebased on the main branch from LLVM. I am working on a rebase that should include the commits fixing this issue, it should happen sometime next week.

**Comment by jeanPerier** [comment]
fir-dev was just rebased on LLVM head https://github.com/flang-compiler/f18-llvm-project/commit/8f681d5b272eeb5c0d13d225313f4ea9517f59f5 that includes the two mentioned commits. Please re-open if this still fails for you.
