### ISSUE TITLE
Missing GETARG

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#795]
It seems that `GETARG` non-standard intrinsic function was omitted from `docs/Intrinsics.md` and `lib/Evaluate/intrinsics.cpp`.

**Comment by Leporacanthicus** [comment]
Workaround: use `GET_COMMAND_ARGUMENT` instead, which is implemented now.

**Comment by oroppas** [comment]
Closing as implemented on llvm ToT.
