### ISSUE TITLE
ieee_arithemetic is missing entries

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#800]
IEEE_Arithmetic is a predefined module.

- [ ] ieee_class
- [ ] ieee_class_type
- [ ] ieee_is_finite
- [ ] ieee_negative_zero
- [ ] ieee_next_after
- [ ] ieee_positive_zero
- [ ] ieee_scalb

**Comment by psteinfeld** [comment]
I'm not sure if I understand the problem.

For the front end, these names are defined in the module "ieee_arithmetic", which is created in the build directory for f18 in the file "<path-to-build-area>/include/flang/ieee_arithmetic.mod".  To make sure that the compiler has access to it, you use the command line option "-I <path-to-build-area>/include/flang".

Here's a sample program that the front end processes without problem:
```
module testIeee
  use ieee_arithmetic
  contains
  function myClass(x)
    type(ieee_class_type) :: myClass
    real, intent(in) :: x
    myClass = ieee_class(x)
  end function myClass
end module
```

**Comment by sscalpone** [comment]
Thanks Pete!  Looks like f18.cpp was updated and the path was removed from the wrapper script.  I'll adjust.
