### ISSUE TITLE
Character array assignment gives wrong result

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18-llvm-project#801]
```
subroutine foo(x, y)
  character(3) :: x(4)
  character(*) :: y(4)
  x = y
end subroutine

  character(3) :: x(4)
  character(3) :: y(4)
  y(1) = "abc"
  y(2) = "def"
  y(3) = "geh"
  y(4) = "ijk"
  call foo(x, y)
  print *, x
end
```
prints `abcbcdcdedef` instead of `abcdefghijkl`.

If `y` is declared as `character(3) :: y(4)` in `foo`, everything works as expected. Most likely an array_coor codegen issue (dynamic length ignored when generating the GEP ? )

**Comment by schweitzpgi** [comment]
See #838
