### ISSUE TITLE
Segfault when using ANY() with a negative stride

### ISSUE THREAD

**Issue by mikaoP** [flang-compiler/f18-llvm-project#832]
I've used fir-dev and the segfault I see is in https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/runtime/tools.h#L47 with `p` being zero

```fortran
PROGRAM P
    IMPLICIT NONE    
    INTEGER :: I
    INTEGER, PARAMETER :: N = 2000
    INTEGER :: A(N)
    INTEGER :: L, U, S
    A = 0
    L = 2000
    U = 1
    S = -1
    DO I=L, U, S
        A(I) = A(I) + 1
    END DO
    IF(ANY(A(::S) /= 1)) STOP -1

END PROGRAM P 
```

**Comment by jeanPerier** [comment]
Not an ANY issue. Lowering is not computing the extent of `A(::-1)` correctly. According to 9.5.3.3.2 point 4, it should be zero, but lowering is computing and propagating a negative extent.
Working on a fix.

**Comment by jeanPerier** [comment]
Fixed in fir-dev (example program now does nothing as expected).
