### ISSUE TITLE
OpenMP: Symbol not mapped into an internal procedure

### ISSUE THREAD

**Issue by mikaoP** [flang-compiler/f18-llvm-project#833]
The following command reports a "symbol not mapped" fatal error because X is not mapped before doing the omp directive data sharing binding. If `X = 3`  is uncommented `bbc` compiles.
```fortran
PROGRAM P
        IMPLICIT NONE
        INTEGER :: X
CONTAINS
        SUBROUTINE S()
                IMPLICIT NONE
!                X = 3
                !$OMP PARALLEL FIRSTPRIVATE(X)
                X = 4
                !$OMP END PARALLEL
        END
END
```
I've used `fir-dev` to compile and `bbc -emit-fir -fopenmp f1.f90` to compile

**Comment by kiranchandramohan** [comment]
Thanks @mikaoP for the report. We are in the process of implementing support for data-sharing clauses like firstprivate. I will check why it segfaults currently.

**Comment by kiranchandramohan** [comment]
This works fine in llvm-project main branch. Closing. Thanks for the report.
