### ISSUE TITLE
Flang driver required: Files that require preprocessing

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#85]
My mock driver fails to preprocess x.F files. We need a flang driver.

**Comment by sscalpone** [comment]
IDK if my sandbox f18 is a suitable replacement for bbc.  (I copied over the parts of bbc that set up and call the mlir and llvm passes.)

**Comment by klausler** [comment]
The f18 parser always runs its preprocessor as part of the prescanning pass, though; it's not an optional feature that has to be enabled.  Are you driving the front-end with code similar to that in the throwaway driver?

**Comment by schweitzpgi** [comment]
Still needed but closing with workaround for now.
