### ISSUE TITLE
semantic error: No explicit type declared for 'dfloat'

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#854]
`flang` lacks the support of `dfloat`

https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gfortran/DFLOAT.html

https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/c-to-d/dfloat.html

```
./dfloat.f90:9:11: error: No explicit type declared for 'dfloat'
        x = dfloat(i)
            ^^^^^^
```

```fortran
      program main

      implicit none
      integer :: i
      double precision :: x

      i = 1
      x = dfloat(i)

      end
```

**Comment by schweitzpgi** [comment]
This is a non-standard intrinsic that maps to one of the variants of the DBLE intrinsic family.

**Comment by psteinfeld** [comment]
I tested this program on nvfortran, GNU, NAG, Intel, and IBM.  All of them compile it successfully except for NAG, which emits a similar error to the one we emit.

**Comment by klausler** [comment]
I think that we should support it.  It appears in legacy code, is easy, and supporting it wouldn't break anything that we're not allowed to break.

**Comment by psteinfeld** [comment]
@klausler is working on this.

**Comment by oroppas** [comment]
I can confirm it's cherry-picked. Thanks!
