### ISSUE TITLE
Character array expressions failures

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18-llvm-project#867]
**1. Scalars in character array expressions are failing because array value copy fail to find there length.**
Repro:

```fortran
subroutine foo(x, y)
  character(*) :: x(4), y
  x = y
end subroutine
```

Crash at compile time, related error messages: "LLVM ERROR: unexpected buffer"
Crash happens: `recoverTypeParams` ([here](https://github.com/flang-compiler/f18-llvm-project/blob/5c35caf49e409bc0c67c789a428bd0b046eb02fb/flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp#L549)) because the scalar value was not generated with one of the expected op.

Suggested fix:
   a. use array_coor to compute character scalar address (the length will be accessible). This may be fragile, there may be other 
      scenario where scalars are lowered in a way that do not carry the length.  `recoverTypeParams` is probably fragile.
   b. provide both rhs and lhs character lengths to the array-update-op, so that we are sure to have them and do not have to 
       assume how a value is produced to get its length.

**2. Non contiguous arrays in array expressions are failing because array value copy fails to retrieve the length (it should be read inside the box if not in the type).**

Repro:
```fortran
module mtest
contains
subroutine foo(x, y)
  character(*) :: x(4)
  character(*) :: y(:)
  x = y
end subroutine
end module
 use mtest
 character(2) :: y1(4) = ["ab", "cd", "ef", "gf"]
 character(3) :: x1(4)
 character(3) :: y2(4) = ["abc", "def", "ghi", "jkl"]
 character(2) :: x2(4)
 call foo(x1, y1)
 print *, x1
 call foo(x2, y2)
 print *, x2
end
```

Compiles but prints nothing instead of the expected:
```
ab cd ef gf 
abdeghjk
```
Root cause: `recoverTypeParams` returns empty params, recoverCharLen returns empty mlir::Value. This result in `genCharacterCopy` using -1 (unknow length in fir.char type) ([here](https://github.com/flang-compiler/f18-llvm-project/blob/5c35caf49e409bc0c67c789a428bd0b046eb02fb/flang/include/flang/Optimizer/Transforms/Factory.h#L108)) as the rhs length.

Possible fix: read length in fir.box if needed.
 
**3. Potential unhandled rhs/lhs overlap due to character scalars in memory** 
There is a potential risk that array expressions misses potential overlap with scalar characters (like in `x = x(1)`) because, as opposed to other intrinsic types, such scalars are handled in memory, not as ssa values. Some tests is required to ensure everything is OK there.

Once 1. and 2. are fixed, it must be ensured that the following program is working (printing "zazazaza" and not "zazzzzzz"):

```fortran
subroutine foo(x)
  character(*) :: x(4)
  x = "z" // x(1)
end subroutine
  character(2) :: x(4) = ["a ", "b ", "c ", "d "]
  call foo(x)
  print *, x
end
```

**Comment by schweitzpgi** [comment]
Works for me.
