### ISSUE TITLE
fatal Fortran runtime error(./f18-ec7e.f90:3): Invalid character '$' in FORMAT

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#886]
`flang` is able to compile and generate executable of the following code

```fortran
      program test_read

      double precision :: x

      write (6, '(9hEnter x: $)')
      read (5, *) x
      print *, x

      end
```

but it hit the runtime error.

**Comment by vdonaldson** [comment]
This enhancement is implemented in the compiler, but it has not been implemented in the runtime library.

**Comment by klausler** [comment]
It's in the runtime as well, but I don't know whether that change has percolated into this repository.

**Comment by vdonaldson** [comment]
This should be resolved then after the next repo rebase.  That will probably not happen right away.

**Comment by oroppas** [comment]
#932 resolved this issue.
