### ISSUE TITLE
sqrt(real(kind=16)) cannot be folded on host

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#900]
`flang-new -fc1 -fdefault-real-8 cannot_be_folded_on_host.f90`

prints the error message

```
./cannot_be_folded_on_host.f90:14:9: sqrt(real(kind=16)) cannot be folded on host
      r = sqrt(abs(d))
          ^^^^^^^^^^^^
```

but `gfortran -c -fdefault-real-8 cannot_be_folded_on_host.f90`doesn't. 

`cannot_be_folded_on_host.f90` looks like following:

```fortran
module foo

implicit none

contains

  subroutine bar(ceff)

    integer, parameter        :: dp = kind(0.0D0)
    real(kind=dp), intent(in) :: ceff(3)
    real(dp)                  :: r, d

    d = ceff(2)*ceff(2) - 4.0D0*ceff(1)*ceff(3)
    r = sqrt(abs(d))

  end

end
```

Which one is the correct behavior?

**Comment by klausler** [comment]
We now correctly fold SQRT for all kinds of real; confirmed in fir-dev.  Closing bug.
