### ISSUE TITLE
fatal Fortran runtime error(./f18-570e.f90:4): End of file during input

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#908]
During LAPACK tests, one of the tests inexplicably failed even though the results looked good.
It turns out that `flang`'s runtime is unable to handle the file with no `EOL`.

```fortran
      PROGRAM MAIN

      IMPLICIT NONE
      INTEGER A, B, C

      READ(5, *) A, B, C

      END
```

`flang read.f` and run

```
./a.out < noeol.in

fatal Fortran runtime error(./f18-1c52.f90:4): End of file during input
Aborted
```

where `noeol.in` looks like

```
0 0 0
```

but 

```
tail -c 1 < noeol.in 
0
```

indicating that no `EOL` at the end of file. Please note that `gfortran` does not have this issue.

**Comment by klausler** [comment]
I'll take a look soon.

**Comment by klausler** [comment]
https://reviews.llvm.org/D106321

**Comment by oroppas** [comment]
@klausler I can confirm the fix.

**Comment by oroppas** [comment]
Closing by #932.
