### ISSUE TITLE
Possible runtime I/O bug

### ISSUE THREAD

**Issue by oroppas** [flang-compiler/f18-llvm-project#911]
This is possibly related to the segfaults observed during LAPACK tests

```
Segmentation fault      /home/ryuta/workspace/flang/lapack/build-flang/bin/xeigtsts < svd.in > ssvd.out
```

with the offending line

```
        READ( NIN, FMT = '(A80)', END = 380 )LINE
```

I suspect a bug in I/O runtime. I set up the following code to inspect what is going on.

```fortran
      PROGRAM READ_CHAR

      IMPLICIT NONE

      CHARACTER*80 LINE

      READ( 5, FMT = '(A80)', END = 380 )LINE
      PRINT *, '-----'
      PRINT *, LINE(1:78)
      PRINT *, '-----'
      PRINT *, LINE(1:79)
      PRINT *, '-----'
      PRINT *, LINE(1:80)
      PRINT *, '-----'

  380 CONTINUE
      END
```

with input 

```
SVD:  Data file for testing Singular Value Decomposition routines
```

and run to see what `READ` is reading

```
./a.out < input 
 -----
 SVD:  Data file for testing Singular Value Decomposition routines             
 -----
 SVD:  Data file for testing Singular Value Decomposition routines             
  
 -----
 SVD:  Data file for testing Singular Value Decomposition routines             
   
 -----
```

It appears `flang` is reading redundant newline. `gfortran` does not have this issue.

This issue may or may not be directly related to the segmentation faults in LAPACK tests, but this is the closet I can dig so far.

**Comment by klausler** [comment]
f18 isn't reading a newline, but it is wrapping output of a character value over multiple lines when more than 78 columns are required.  That doesn't seem right, and I'll fix it, but I don't think that this is the source of your original problem.

**Comment by oroppas** [comment]
@klausler Thanks for taking care of newline reading.
Yeah, you're right. `FORT_FMT_RECL=100` didn't fix the issue of LAPACK test I/O.
I need to dig deeper.

**Comment by klausler** [comment]
If there is no bug to be fixed here, please close this issue.  Let me know if I can help isolate your problem.

**Comment by oroppas** [comment]
I'll open the new case once I isolate the issue.
