### ISSUE TITLE
character arrays and substrings

### ISSUE THREAD

**Issue by vdonaldson** [flang-compiler/f18-llvm-project#924]
See tests:
 - nag_f95_handbook/f74.f90
 - nag_f95_iso1539/ch6egs1.f90
 - nag_f95_syntax/615t621.f90
 - nag_f95_top95/e12.f90

```
  character(10) school(5)
  
  ! bad result:  middle./sumiddle./sumiddle./sumiddle./sumiddle./su
  school = "middle"
  print*, school

  ! bad result:  middle./smiddle./sumiddle./sumiddle./su middle./s
  school = ' '
  school(2:4) = "middle"
  print*, school

  ! bad result:  middle./s mmiddle s middle./s middle./s middle./s
  school = ' '
  school(2)(3:9) = "middle"
  print*, school

  ! compiler crash:  not yet implemented unhandled substring base type
  school = ' '
  school(2:4)(3:9) = "middle"
  print*, school

  end
```

**Comment by jeanPerier** [comment]
@schweitzpgi , I am not sure fir.slice can describe array substring. Do you see a way to do it, or should the fir.slice op be extended to support it, or lowering should be the one dealing with it somehow (not quite sure how).

Note that issue #867 is also impacting character expressions without substring and may cause trouble in the program above (#894 is fixing this issue, but won't help with substring that needs additional work).

**Comment by vdonaldson** [comment]
The test case above now compiles and executes correctly.
Tests ch6egs1.f90 and e12.f90 now compile and execute correctly.
Tests f74.f90 and 615t621.f90 no longer abort at compile time.
They now compile and execute, but output fails verification checks.
Close in favor of addressing additional issues elsewhere.
