### ISSUE TITLE
allocatable components

### ISSUE THREAD

**Issue by vdonaldson** [flang-compiler/f18-llvm-project#925]
Execution of `nag_correct/nag_f08_f95` tests `q0a.f90` and `q0b.f90` fail at runtime.

Failure output with production library code is `"Invalid descriptor"`

Failure output with debug library code is:
`"Internal error: RUNTIME_CHECK(zeroBasedDim >= 0 && zeroBasedDim < descriptor.rank()) failed"`

Test `q0b.f90`:

```
program mtest1
 type data1
  integer i
  integer j
 end type
 type data2
  type(data1), allocatable :: d1(:)
 end type
 type data3
  type(data2), allocatable :: d2(:)
 end type
 call s
contains
  recursive subroutine s
    type(data3) :: d3
    allocate(d3%d2(10))
    allocate(d3%d2(2)%d1(10))
  end subroutine
end program
```

**Comment by jeanPerier** [comment]
I am not entirely surprised, allocatable components are F2003 and not handled correctly yet in lowering (they are not initialized and assigned as they should). We should probably add a high level TODO for them before upstreaming to avoid weird bug reports related to this half-implemented feature.

**Comment by jeanPerier** [comment]
Issue fixed by implementation of static variables default initialization (#963) that was required by the allocatable components. q0a.f90 and q0b.f90 now pass.
