### ISSUE TITLE
The CpuTime intrinsic test fails intermittently

### ISSUE THREAD

**Issue by psteinfeld** [flang-compiler/f18-llvm-project#930]
In a run where I executed check-flang 10,000 times, this test failed twice, once at run 4410 and the second time at run 5792.  Both cases had similar output.  Here's the log file from one of the failing sessions:
```
FAIL: flang-Unit :: RuntimeGTest/./FlangRuntimeTests/TimeIntrinsics.CpuTime (915 of 983)
******************** TEST 'flang-Unit :: RuntimeGTest/./FlangRuntimeTests/TimeIntrinsics.CpuTime' FAILED ********************
Script:
--
/local/home/psteinfeld/f18/cshift/flang/Release/unittests/RuntimeGTest/./FlangRuntimeTests --gtest_filter=TimeIntrinsics.CpuTime
--
Note: Google Test filter = TimeIntrinsics.CpuTime
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TimeIntrinsics
[ RUN      ] TimeIntrinsics.CpuTime
../unittests/RuntimeGTest/Time.cpp:34: Failure
Expected: (end) > (start), actual: 3.664519e-03 vs 3.664519e-03
[  FAILED  ] TimeIntrinsics.CpuTime (0 ms)
[----------] 1 test from TimeIntrinsics (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TimeIntrinsics.CpuTime

 1 FAILED TEST

```

**Comment by klausler** [comment]
My guess is that the process was migrated between sockets.  The test should not assume monotonicity when the CPUID changes, or be run with a singleton cpumask to prevent migration.

**Comment by rovka** [comment]
Is this on a current version of the test? 
At the moment we have [ASSERT_GE](https://github.com/flang-compiler/f18-llvm-project/blob/402461beb051b6a5c158f1e36d8e2c2b676e8804/flang/unittests/RuntimeGTest/Time.cpp#L26) between start and end, so it shouldn't fail in this way. The change for that was merged upstream on [the 18th of June](https://github.com/flang-compiler/f18-llvm-project/commit/4498137bd7857c07921b4cd6313baac62ead24e2), but maybe it took a while to get here?

**Comment by psteinfeld** [comment]
Sorry the change to `ASSERT_GE` fixed this, and we should have closed this issue.  I'm closing it now.

**Comment by psteinfeld** [comment]
Closed by https://github.com/flang-compiler/f18-llvm-project/pull/944
