### ISSUE TITLE
maxloc with a dim argument fails at runtime

### ISSUE THREAD

**Issue by vdonaldson** [flang-compiler/f18-llvm-project#934]
See test `nag_f95_iso1539/apdxc_9_5.f90`

The following test fails at runtime:

```
    real :: a(5)
    a = 1.1
    a(3) = 2.2
    i = maxloc(a, dim=1)
    print*, i
  end
```

`fatal Fortran runtime error(.../flang/runtime/reduction-templates.h:200): Internal error: RUNTIME_CHECK(at[0] == 1) failed at .../flang/runtime/reduction-templates.h(200)`

**Comment by mleair** [comment]
Pull Requet #957 fixes this issue.
