### ISSUE TITLE
User defined assignment in FORALL hits "symbol is not mapped"

### ISSUE THREAD

**Issue by jeanPerier** [flang-compiler/f18-llvm-project#970]
Causes 5 nag tests to fail in nag_f08_f95: k2.f90, m8.f90, nic.f90, p4.f90, p6.f90

```
  interface assignment(=)
    pure subroutine s(a,b)
      logical,intent(out) :: a
      integer,intent(in) :: b
    end
  end interface
  logical :: x(10)
  forall(i=1:2) x(i) = i
end
```

Hits error: "symbol is not mapped to any IR value". The unmapped symbol is the FORALL index `i` that is referenced in the user defined assignment call expression build by the front-end for the user assignment (`s(x(int(i,kind=8)),i)`).

I believe the root cause is that the `ev::Assignment` lowering case for user defined assignment is raising the call to an array expression if there is an explicit context here:  https://github.com/flang-compiler/f18-llvm-project/blob/79dd7cc4127fb4dffea14350a21c7833451c1248/flang/lib/Lower/Bridge.cpp#L1903

Though, this will most likely require implementing elemental subroutine call support to implement this.

**Comment by schweitzpgi** [comment]
No longer see the symbol not in map. Closing.
